<h1>Table des matières<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Calculs-de-base" data-toc-modified-id="Calculs-de-base-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Calculs de base</a></span></li><li><span><a href="#Sept-grands-types-de-variables" data-toc-modified-id="Sept-grands-types-de-variables-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Sept grands types de variables</a></span><ul class="toc-item"><li><span><a href="#Nombres-entiers" data-toc-modified-id="Nombres-entiers-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Nombres entiers</a></span></li><li><span><a href="#Nombres-décimaux" data-toc-modified-id="Nombres-décimaux-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Nombres décimaux</a></span></li><li><span><a href="#Booléens" data-toc-modified-id="Booléens-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Booléens</a></span></li><li><span><a href="#None" data-toc-modified-id="None-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>None</a></span></li><li><span><a href="#Texte" data-toc-modified-id="Texte-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Texte</a></span><ul class="toc-item"><li><span><a href="#Transformations-de-types" data-toc-modified-id="Transformations-de-types-2.5.1"><span class="toc-item-num">2.5.1&nbsp;&nbsp;</span>Transformations de types</a></span></li><li><span><a href="#Fonctions-et-méthodes-utiles-pour-traiter-du-texte" data-toc-modified-id="Fonctions-et-méthodes-utiles-pour-traiter-du-texte-2.5.2"><span class="toc-item-num">2.5.2&nbsp;&nbsp;</span>Fonctions et méthodes utiles pour traiter du texte</a></span></li><li><span><a href="#La-notion-d'«index»" data-toc-modified-id="La-notion-d'«index»-2.5.3"><span class="toc-item-num">2.5.3&nbsp;&nbsp;</span>La notion d'«index»</a></span></li></ul></li><li><span><a href="#Listes" data-toc-modified-id="Listes-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Listes</a></span><ul class="toc-item"><li><span><a href="#Fonctions-et-méthodes-relatives-aux-listes" data-toc-modified-id="Fonctions-et-méthodes-relatives-aux-listes-2.6.1"><span class="toc-item-num">2.6.1&nbsp;&nbsp;</span>Fonctions et méthodes relatives aux listes</a></span></li><li><span><a href="#Notion-d'index-avec-les-listes" data-toc-modified-id="Notion-d'index-avec-les-listes-2.6.2"><span class="toc-item-num">2.6.2&nbsp;&nbsp;</span>Notion d'index avec les listes</a></span></li></ul></li><li><span><a href="#Dictionnaires" data-toc-modified-id="Dictionnaires-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Dictionnaires</a></span></li></ul></li><li><span><a href="#Boucles" data-toc-modified-id="Boucles-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Boucles</a></span><ul class="toc-item"><li><span><a href="#Boucles-for" data-toc-modified-id="Boucles-for-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Boucles <code>for</code></a></span><ul class="toc-item"><li><span><a href="#La-notion-de-compteur" data-toc-modified-id="La-notion-de-compteur-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>La notion de compteur</a></span></li></ul></li><li><span><a href="#Boucles-while" data-toc-modified-id="Boucles-while-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Boucles <code>while</code></a></span></li></ul></li><li><span><a href="#Conditions" data-toc-modified-id="Conditions-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Conditions</a></span></li></ul></div>

# Python 1 - Principes fondamentaux

<p style="font-size:1.5em">Carnet commenté des notions présentées lors du premier cours d'initiation au langage Python, le 7 mai 2020, par Zoom.</p>
<hr>

<h3 style="background:pink;text-align:center;padding:10px">Calculs de base</h3>

Python permet notamment d'effectuer toutes sortes de calculs. Des plus simples...

In [1]:
2+2

4

... aux plus complexes

In [2]:
87656454345345354*876545678976546789765

76834886290817418559209302118957501810

Pour exprimer des exposants, on utilise deux astérisques consécutifs.

In [3]:
10**9

1000000000

L'opérateur **modulo (```%```)** nous donne le nombre entier qu'il reste après la division d'un nombre par un autre.

Par exemple, **101%2** va donner 1 parce que si on divise 101 par 2, le nombre entier qu'on obtient est 50 et il nous reste 1.

In [4]:
101%2

1

Si on fait 100%2, il nous reste 0.

C'est ainsi que modulo peut être utile si on cherche à déterminer si un nombre est pair ou impair. Si le résultat d'un %2 est 0, on est en présence d'un nombre pair, si le résultat est 1, on est alors en présence d'un nombre impair.

In [5]:
100%2

0

<h3 style="background:pink;text-align:center;padding:10px">Sept grands types de variables</h3>

Les variables sont des contenants. Le contenu qu'on y place détermine le type que prendra cette variable.

Vous pouvez donnez à vos variables les noms que vous voulez. Choisissez les noms les plus descriptifs possibles. Par convention, tâchez de ne donner que des noms en minuscules. Si le nom que vous souhaitez donner comporte plusieurs mots, séparez-les par une barre de soulignement (```nom_de_variable```) ou en mettant en majuscules la première lettre de tous les mots, sauf le premier (```nomDeVariable```).

**Évitez aussi de mettre des accents dans vos noms de variables**.

Il y a plusieurs types de variables possibles en python. On va voir les sept plus usités, dans mon expérience.

<h4 style="background:cyan;text-align:center;padding:10px">Nombres entiers</h4>

Dans l'exemple ci-dessous, on place, à l'aide de l'opérateur ```=``` le nombre entier 55 dans la variable ```a```.

In [6]:
a = 55

In [7]:
a

55

Ce faisant, la variable ```a``` est donc de type ```int``` pour *integer* (la traduction anglaise de **nombre entier**).

On peut afficher de quel type est une variable en utilisant la **fonction** ```type```. Vous remarquerez, au passage, que le mot ```type``` prend une coloration différente dans votre carnet. C'est parce qu'il s'agit d'un mot réservé. Évitez de donner à vos variables des noms réservés comme celui-ci.

In [8]:
type(a)

int

<h4 style="background:cyan;text-align:center;padding:10px">Nombres décimaux</h4>

Les nombres décimaux sont un type distinct de variable. Alors qu'en français, la décimale est marquée par une virgule, en python il faut utiliser un point.

Les variables ```b``` et ```c```, ci-dessous, contiennent respectivemnt les nombres 7,8 et 9,482758620689655. Elles sont de type ```float```, ce qui signifie *floating-point number*, ou nombre à [virgule flottante](https://fr.wikipedia.org/wiki/Virgule_flottante) en français.

In [9]:
b = 5.8
type(b)

float

In [10]:
c = a/b
c

9.482758620689655

In [11]:
type(c)

float

<img src="https://journalisme.uqam.ca/wp-content/uploads/sites/77/2020/05/bonus.png" style="text-align:center">

Si vous avez besoin d'arrondir des nombres décimaux, utilisez la fonction ```round```.

Elle nécessite deux arguments: le nombre à arrondir et le nombre de chiffres à conserver après la virgule.

In [12]:
round(c,3)

9.483

<h4 style="background:cyan;text-align:center;padding:10px">Booléens</h4>

Vous connaissez certainement la [logique booléenne](https://fr.wikipedia.org/wiki/Alg%C3%A8bre_de_Boole_(logique)). Elle s'applique de différentes façons en programmation. L'une d'entre elles concerne directement les variables puisque peuvent être de type booléen. Dans ces cas, elle ne pourront prendre que deux valeurs: **```True```** (vrai) ou **```False```** (faux). Remarquez les majuscules dans ces valeurs.

In [13]:
x = True
y = False

In [14]:
type(x), type(y)

(bool, bool)

<h4 style="background:cyan;text-align:center;padding:10px">None</h4>

Le néant existe-t-il? La question [déclenche des passions chez les philosophes](https://fr.wikipedia.org/wiki/L%27%C3%8Atre_et_le_N%C3%A9ant).

En informatique, on a réglé ça vite fait. Le néant existe.

C'est ainsi que des variables peuvent avoir une valeur vide, **```None```**, dont il faut que je vous parle parce que vous risquez de la croiser un peu plus tard dans le cours. Il arrive en effet, quand on fait du moissonnage de données, que ce qu'on avait prévu mettre comme valeur dans une variable ne se trouve pas, finalement, dans le site dans lequel on va chercher ces données. Notre variable va exister, mais ne contiendra rien. Elle sera de type ```NoneType```.

In [15]:
sartre = None

In [16]:
type(sartre)

NoneType

<h4 style="background:cyan;text-align:center;padding:10px">Texte</h4>

On peut aussi mettre du texte dans une variable. Toute suite de caractères se trouvant entre deux guillemets anglais (```"``` ou *double quotes*; attention de ne pas utiliser les guillemets français) est considérée comme du texte en python. On peut aussi utiliser les apostrophes (```'``` ou *single quotes*), mais préférez généralement les guillemets anglais.

Par exemple, la variable ```d``` contient une expression contemporaine.

In [17]:
d = "Ça va bien aller!"
d

'Ça va bien aller!'

La variable ```e``` contient également du texte.

In [18]:
e = " nous dit Horacio Arruda"
e

' nous dit Horacio Arruda'

Comme ce texte semble suivre celui de la variable ```d```, on peut le concaténer à cette dernière avec un simple ```+``` et mettre le résultat dans une nouvelle variable, qu'on peut appeler ```f```.

In [19]:
f = d + e
f

'Ça va bien aller! nous dit Horacio Arruda'

Maintenant, le contenu de certaines variables peut nous laisser perplexe.

La variable ```annee``` (vous avez remarqué, pas d'accent aigu) contient-elle du **texte** ou un **nombre entier**?

In [20]:
annee = "2020"

La présence des guillemets anglais, ici, nous nonne la réponse, confirmée par la fonction ```type```.

In [21]:
type(annee)

str

Mais parfois, quand on code, on n'est pas toujours en mesure de voir que des variables dont on pense qu'elles sont des nombres sont en fait du texte.

On peut alors être tenté d'effectuer des calculs avec ces «faux nombres», ce qui génère le message d'erreur ci-dessous.

In [22]:
tokyo = annee + 1

TypeError: must be str, not int

Lisez bien ces messages d'erreur. Ils contiennent des indices sur ce qui a planté.

Ici, le message vous dit: ```TypeError: must be str, not int```.

On est en présence d'une erreur sur le type (```TypeError```). Python nous dit que ça doit être en raison d'une variable de type texte (```str```) alors qu'il s'attend à un nombre entier (```int```).

Hmmm... Quoi faire?

<h5 style="background:beige;text-align:center;padding:10px">Transformations de types</h5>

Dans un cas comme celui-ci, on peut changer le type de la variable ```annee```. Les types de variables sont aussi des fonctions. Ainsi, il suffit d'utiliser la fonction ```int``` pour transformer le *texte 2020* en *nombre 2020*.

In [23]:
annee = int(annee)
type(annee)

int

Attention, ça ne fonctionne que si on est en présence de nombres. Les transformations ci-dessous vont échouer car les textes qu'on tente de transformer contiennent des caractères qui ne sont pas des nombres.

In [24]:
int("en 2020")

ValueError: invalid literal for int() with base 10: 'en 2020'

In [25]:
int("deux mille vingt")

ValueError: invalid literal for int() with base 10: 'deux mille vingt'

In [26]:
int("twenty twenty")

ValueError: invalid literal for int() with base 10: 'twenty twenty'

<img src="https://journalisme.uqam.ca/wp-content/uploads/sites/77/2020/05/bonus.png" style="text-align:center">

In [27]:
int("7E4",16)

2020

Ah, tiens! La fonction ci-dessus fonctionne alors qu'on a transformé une chaîne de caractères contenant un «E». Il faut simplement savoir que la fonction ```int``` peut contenir un 2e argument qui précise la base dans laquelle se trouve le «nombre de type texte» qu'on souhaite transformer. Par défaut, il s'agit de la base 10. Mais dans le cas ci-dessus, «7E4» est un nombre hexadécimal (base 16) et ```int``` le transforme en un nombre en base 10, à savoir 2020.

<h5 style="background:beige;text-align:center;padding:10px">Fonctions et méthodes utiles pour traiter du texte</h5>

Il y a [des myriades de fonctions et de méthodes qui vous permettent de traiter des variables de type texte](https://www.w3schools.com/python/python_ref_string.asp). Voici quelques-unes de celles dont je me sers le plus souvent.

<p style="text-align:center">***</p>

La fonction ```len()``` est pratique si on a besoin de connaître le nombre de caractères dans un texte. Dans le bloc de code ci-dessous, je vais mettre le texte des objectifs du cours dans la variable ```objectifs``` et je vais en compter la longueur.

In [28]:
objectifs = "L'objectif général est de former une prochaine génération de chercheurs apte à créer ses propres outils numériques et à comprendre les avantages, mais aussi les limites, de l'informatique en général et de l'«intelligence artificielle» (IA) en particulier dans un contexte de recherche dans toutes les disciplines (sciences, sciences humaines et sociales, etc.)."
len(objectifs)

361

Ce texte a donc 361 caractères, espaces incluses.

<img src="https://journalisme.uqam.ca/wp-content/uploads/sites/77/2020/05/bonus.png" style="text-align:center">

Certaines des fonctions que je vais vous présenter ci-dessous sont en fait des **méthodes**. Méthodes et fonctions sont similaires. On reconnaît les méthodes parce qu'elles commencent par un point qui suit le nom de la variable à laquelle on les applique. Les fonctions prennent des variables comme arguments entre parenthèses. Comme les méthodes aussi peuvent inclure des variables parmi les arguments qu'on peut inclure entre leurs parenthèses, cela en fait aussi des fonctions... Il n'y aura aucune question d'examen sur ces notions. Je vous en parle simplement par souci de correctement nommer les choses. 🤓

<p style="text-align:center">***</p>

Jusqu'ici, vous avez remarqué: le simple fait d'écrire le nom d'une variable suffit pour que votre carnet en affiche le contenu.

Habituellement, cependant, on utilise la fonction ```print()``` pour afficher des variables. Cette fonction marche avec tout type de variable, pas uniquement les variables de type texte. Mais je vous en parle maintenant pour vous présenter la méthode ```.format()```. Celle-ci permet de formater l'affichage d'une variable texte pour y insérer d'autres variables. Je vous donne un exemple.

Vous travaillez sur des publications dans les réseaux sociaux. Le nombre de partages de chaque publications est dans une variable appelée ```partages```. Pour insérer ce nombre dans un affichage plus intéressant vous pourriez écrire ce code:

In [29]:
partages = 82
print("La publication a été partagée {} fois".format(partages))

La publication a été partagée 82 fois


Vous remarquez que dans votre texte se trouve une paire d'accolades (```{}```). C'est un **espace réservé** (ou *placeholder*) qui indique où placer la variable que vous donnez comme argument à la méthode ```.format()```.

Vous pouvez insérer autant de variables que nécessaire. Voici un autre exemple.

Vous travaillez sur des données médicales. Vous avez un code de patient (car vos données sont anonymisées) et des information sur ses signes vitaux, ainsi que le moment où ceux-ci ont été pris.

In [30]:
code_patient = "j875af&3865DVx33"
age = "28"
date = "2020-05-06"
heure = "11:43"
pression = "122/41"
temp = "37.2"
rythme = "64"

print("Le {}, à {}, le patient {} ({} ans) avait un rythme cardiaque de {} battements par minute, une température de {}° et une pression de {}.".format(date,heure,code_patient,age,rythme,temp,pression))

Le 2020-05-06, à 11:43, le patient j875af&3865DVx33 (28 ans) avait un rythme cardiaque de 64 battements par minute, une température de 37.2° et une pression de 122/41.


La méthode ```.replace()``` vous permet de substituer du texte pour un autre texte. Je m'en sers le plus souvent pour retrancher du texte dans une chaîne de caractères.

Par exemple, admettons que vous ayez à traiter un grand nombre d'URL du *Devoir*, comme celui-ci:

https://www.ledevoir.com/monde/578461/mieux-vaut-prevenir-que-guerir-dit-l-oms
<a href="https://www.ledevoir.com/monde/578461/mieux-vaut-prevenir-que-guerir-dit-l-oms" target="_blank"><img src="https://media2.ledevoir.com/images_galerie/nwd_809240_641278/image.jpg" width="25%"></a>

Vous pourriez placer vos URL dans une variable que vous pourriez baptiser ```url```.

In [31]:
url = "https://www.ledevoir.com/monde/578461/mieux-vaut-prevenir-que-guerir-dit-l-oms"

Mais voilà. Tous ces URL commencent par la même chose: «https://www.ledevoir.com/». Vous souhaitez retrancher ces débuts répétitifs. La méthode ```.replace``` peut vous aider.

Elle demande deux arguments. Le premier est le texte qu'on veut remplacer. Le second est le texte qui remplacera le premier. Dans les cas où on veut retrancher du texte, on le remplace par du texte vide, c'est-à-dire deux guillemets anglais collés l'un sur l'autre: ```""```.

Cela donne ceci:

In [32]:
url = url.replace("https://www.ledevoir.com/","")

Et vous voyez que la valeur de la variable ```url``` a été changée en conséquence:

In [33]:
url

'monde/578461/mieux-vaut-prevenir-que-guerir-dit-l-oms'

Il arrive souvent, quand on moissonne des données dans le web, qu'on se retrouve avec des variables de texte qui comportent plusieurs espaces blancs indésirables au début et à la fin. Voici un exemple:

In [34]:
auteur = "           Agence France-Presse                   "

Utiliser la méthode ```.replace()``` pour remplacer des espaces (```" "```) par du vide (```""```) ne serait pas une solution puisque l'espace entre «Agence» et «France-Presse» disparaîtrait aussi pour donner «AgenceFrance-Presse».

La solution, ici, est la méthode ```.strip()```. Elle décape littéralement les textes des espaces indésirables au début et à la fin d'une variable.

Par défaut, elle vous débarrasse des espaces.

In [35]:
auteur = auteur.strip()
auteur

'Agence France-Presse'

Les méthodes ```.strip()``` et ```.replace()``` sont utiles pour traiter des textes qui représentent des montants ou des pourcentages et qu'on souhaiterait transformer en nombres.

Voici deux exemples. Dans le premier, on a un montant d'un demi-million de dollars (**$500,000**), dans le second, on a un pourcentage exprimé avec une décimale en français (**79,5%**).

On va transformer le premier texte en nombre entier (et le multiplier par 5 pour prouver qu'il s'agit bel et bien un nombre) et le second en nombre décimal (auquel on va retrancher 1,1 pour montrer que ç'a bien marché ici aussi).

Vous allez aussi remarquer qu'on va le faire en une seule opération, car il est possible d'***enchaîner les méthodes les unes après les autres*** et d'***insérer des méthodes dans des fonctions***.

In [36]:
subvention = "$500,000"
subvention = int(subvention.strip("$").replace(",",""))
subvention * 5

2500000

In [37]:
appuis = "79,5%"
appuis = float(appuis.strip("%").replace(",","."))
appuis - 1.1

78.4

<img src="https://journalisme.uqam.ca/wp-content/uploads/sites/77/2020/05/bonus.png" style="text-align:center">

Il existe aussi différentes méthodes pour transformer la casse des textes. Pour vous montrer leur effet, nous allons créer une variable avec du texte.

In [38]:
martino = "Comme Richard Martineau, j'aime parfois TOUT ÉCRIRE EN MAJUSCULES!!!"

La méthode ```.lower()``` transforme tous les caractères de votre texte en minuscules (*lowercase*).

In [39]:
martino.lower()

"comme richard martineau, j'aime parfois tout écrire en majuscules!!!"

La méthode ```.upper()``` fait l'inverse et transforme tous les caractères de votre texte en majuscules (*uppercase*).

In [40]:
martino.upper()

"COMME RICHARD MARTINEAU, J'AIME PARFOIS TOUT ÉCRIRE EN MAJUSCULES!!!"

La méthode ```.capitalize()```, pour sa part, ne met une majuscule qu'au tout premier caractère de la chaîne.

In [41]:
martino.capitalize()

"Comme richard martineau, j'aime parfois tout écrire en majuscules!!!"

Enfin, une dernière méthode juste pour vous: ```.count()``` permet de compter le nombre d'occurrences d'un caractère ou d'une chaîne de caractères dans une variable texte donnée.

Par exemple, créons la variable ```justin``` contenant le texte d'un [récent discours du premier ministre canadien](https://pm.gc.ca/fr/nouvelles/discours/2020/05/05/allocution-du-premier-ministre-annoncer-aide-supplementaire-au).

In [42]:
justin = "Bonjour à tous. Avant de commencer, je tiens à souligner qu’aujourd’hui marque le 75e anniversaire de la libération des Pays-Bas. En ce jour, on se souvient des Canadiens et des Terre-Neuviens qui ont libéré les Pays-Bas de la tyrannie des nazis. On souligne les liens étroits qui ont été forgés entre le Canada et les Pays‑Bas. Et on rend hommage au courage incroyable et aux sacrifices de nos anciens combattants, à qui on est à tout jamais reconnaissant. En période de crise, les Canadiens s’entraident les uns les autres et aident nos amis. On l’a constaté il y a 75 ans, sur les champs de bataille de la Seconde Guerre mondiale, et on le constate encore une fois aujourd’hui au cours de cette pandémie. Ces jours-ci, tous ceux qui œuvrent dans le secteur de l’alimentation travaillent plus fort que jamais pour remplir les étagères de nos épiceries. Ils continuent de faire de longues heures pour nous nourrir, mais la pandémie complique la tâche. Les travailleurs doivent prendre des mesures supplémentaires pour se protéger. Ils doivent changer leurs façons de faire et respecter la distanciation physique. Et puisque les hôtels et les restaurants sont fermés, de nombreux producteurs se retrouvent avec des surplus importants de certains produits. Depuis le début, on a dit qu’on allait être là pour ceux qui ont besoin d’un coup de main. Donc aujourd’hui, on annonce un nouvel investissement de plus de 252 millions de dollars pour aider le secteur agroalimentaire à traverser cette crise. De cette somme, on va allouer plus de 77 millions de dollars aux transformateurs alimentaires pour protéger la sécurité de leurs travailleurs. C’est de l’argent qu’ils vont pouvoir utiliser pour acheter plus d’équipement de protection personnelle, adapter leurs protocoles sanitaires et appuyer d’autres mesures de distanciation sociale. Ça va aussi permettre aux transformateurs d’adapter leurs usines de façon à ce qu’on puisse produire plus de produits au Canada. Pour aider les éleveurs de bétail et de porc, on met sur pied des initiatives nationales sous Agri-relance, qui disposera d’une enveloppe pouvant atteindre 125 millions de dollars pour aider les producteurs à s’adapter aux changements du marché. Les fermes et les porcheries élèvent plus d’animaux que notre système peut transformer en produits de consommation comme du steak et du bacon à cause de la COVID-19. Donc on doit garder les animaux sur la ferme plus longtemps que prévu – et ça coûte cher. Les fonds qu’on annonce aujourd’hui vont aider les producteurs de bœuf et de porc à s’adapter à cette crise. C’est un premier investissement et si on doit en faire plus, on va en faire plus. Pour ce qui est des producteurs laitiers, on compte travailler avec tous les partis à la Chambre pour augmenter de 200 millions de dollars la ligne de crédit de la Commission canadienne du lait. La Commission a déjà un programme en place pour entreposer et conserver les produits laitiers. Elle entrepose du beurre et du fromage depuis le début de la crise, et elle prévoit atteindre sa capacité maximale bientôt. En augmentant la ligne de crédit de la Commission, on peut éviter de perdre des produits frais de chez nous et aider les producteurs laitiers à composer avec les conséquences de la crise. Puisque les hôtels et les restaurants sont fermés, certains types d’aliments – comme le lait, le beurre et les pommes de terre – sont produits en trop grande quantité. Bien que des dons aient été faits à des banques alimentaires, on n’a pas la capacité en ce moment de redistribuer une quantité aussi importante d’aliments. Et certains producteurs n’ont pas d’autre choix que de jeter leur produit. Cela entraîne un gaspillage de nourriture et une perte de revenus pour les gens qui ont travaillé si fort pour produire ces aliments. Pour éviter ça, on lance le programme d’achat des aliments excédentaires, qui sera doté initialement d’un budget de 50 millions de dollars. Le gouvernement achètera une quantité importante de certains produits qui risquent d’être gaspillés, par exemple des pommes de terre ou de la volaille, et les redistribuera à des organisations qui luttent contre l’insécurité alimentaire. Nos agriculteurs seront donc rémunérés pour leur important travail et des gens vulnérables au Canada auront accès à des aliments frais durant la crise. Ensemble, ces mesures représentent un investissement de 252 millions de dollars à l’appui des gens qui remplissent les étagères de nos épiceries et nourrissent nos familles. Je veux d’ailleurs prendre un moment pour souligner le travail de la ministre Bibeau dans ce dossier. Cela dit, on sait que les agriculteurs s’inquiètent toujours des effets à long terme qu’aura cette pandémie sur leur industrie. Ils s’inquiètent d’avoir assez de travailleurs pour la récolte plus tard dans la saison ou d’avoir suffisamment d’équipement de protection individuelle pour leurs travailleurs. Ce sont des préoccupations valides. Et je peux vous assurer qu’on travaille avec les agriculteurs et les intervenants ainsi qu’avec les provinces et les territoires pour trouver des solutions durables. J’aimerais conclure aujourd’hui en remerciant tous les travailleurs de notre industrie alimentaire. Les gens passent beaucoup de temps dans leur cuisine. Ils préparent des plats pour un voisin âgé ou pour eux-mêmes. Ils découvrent de nouvelles recettes ou essaient de faire du pain au levain. Cuisiner ne sert pas seulement à se nourrir, surtout ces jours-ci. Ça permet également de réduire le stress, de faire partie d’une communauté, de s’appuyer les uns les autres et de créer des souvenirs. Cela est possible grâce aux travailleurs de notre industrie. À tous ceux qui travaillent dans le domaine de l’alimentation – merci pour tout ce que vous faites pour nous. On est là et on va continuer d’être là pour vous. Merci beaucoup."

Si on était curieux de savoir combien de fois M. Trudeau parle de travail ou de travailleurs, on pourrait mettre la chaîne «travail» comme argument de la méthode ```.count()``` et appliquer cette dernière à la variable ```justin``` comme ceci. Et on voit que le PM a parlé 13 fois de travail, de travailler ou de travailleurs dans ce discours.

In [43]:
justin.count("travail")

13

<h5 style="background:beige;text-align:center;padding:10px">La notion d'«index»</h5>

Les ascenseurs européens ont toujours un étage zéro pour ce qu'on désigne, au Québec, comme le «premier étage».

<img src="http://bit.ly/jhroy0" width="25%">

Il en va de même en informatique. Le premier élément d'une série porte toujours le numéro zéro.

C'est ainsi que le premier caractère dans un texte est numéroté zéro. C'est ce qu'on appelle son numéro d'**index**. L'index, dans une variable de type texte, désigne la place d'un caractère dans ce texte.

Allons-y avec la variable ```url``` sur laquelle nous avons travaillé tout à l'heure et qui est toujours en mémoire dans notre carnet.

In [44]:
url

'monde/578461/mieux-vaut-prevenir-que-guerir-dit-l-oms'

Si on veut accéder au premier caractère dans cette variable (en l'occurrence, la lettre «m»), voici ce qu'on devra écrire comme code.

In [45]:
url[0]

'm'

Pour accéder au 2e caractère, on écrirait plutôt ceci:

In [46]:
url[1]

'o'

Il s'agit ainsi d'accompagner le nom de la variable de crochets (```[]```) entre lesquels on indiquera le numéro d'index auquel on souhaite accéder.

Pour accéder au dernier caractère, il n'est pas nécessaire de compter le nombre de caractères avec la fonction ```len()```. On peut demander le numéro d'index -1, et ça fonctionne.

In [47]:
url[-1]

's'

On peut aussi accéder à des **étendues**, des plages d'index.

Par exemple, pour extraire une étendue qui va du 10e au 20e caractère de la variable ```url```, on écrira:

In [48]:
url[10:21]

'61/mieux-va'

Vous avez remarqué que le début et la fin de l'étendue sont séparés par deux-points (```:```) et que la fin de l'étendue n'est pas 20, comme je l'ai demandé, mais 21. C'est que le dernier numéro d'index **n'est pas inclus** dans l'étendue qui nous sera retournée.

Si l'étendue qui nous intéresse commence au premier caractère d'un texte, il n'est pas nécessaire de commencer par zéro. C'est ainsi que les deux codes ci-dessous sont identiques.

In [49]:
url[0:21], url[:21]

('monde/578461/mieux-va', 'monde/578461/mieux-va')

Dans le cas d'une étendue qui se terminerait par le dernier caractère d'un texte, écrire -1 comme fin de l'étendue vous priverait de ce dernier caractère. Ainsi, les deux codes ci-dessous ne produisent pas le même résultat.

In [50]:
url[20:-1], url[20:]

('aut-prevenir-que-guerir-dit-l-om', 'aut-prevenir-que-guerir-dit-l-oms')

On peut faire des recherches dans une variable texte pour connaître le numéro d'index d'un caractère donné ou d'une suite de caractères donnée. Pour ce faire, on peut utiliser la méthode ```.find()```.

Par exemple, lorsqu'on travaille avec des URL, on peut avoir besoin de connaître l'emplacement des barres obliques.

Si on applique la méthode ```.find()``` à notre variable ```url``` pour trouver le caractère «/», par exemple, on écrira:

In [51]:
url.find("/")

5

Ce code nous retourne «5», ce qui est le numéro d'index de la première barre oblique qu'on rencontre dans la variable ```url```.

On pourrait utiliser la méthode ```.find()``` pour extraire le début de notre variable url, qui contient le nom de la section du *Devoir* dans laquelle est classée l'article dont on est allé chercher l'URL. 

In [52]:
url[:url.find("/")]

'monde'

Cette méthode peut être utile si on souhaite extraire le nom de la section de plusieurs URL.

Voyez avec cet autre URL tiré du *Devoir*, qu'on va appeler ```url2```:

In [53]:
url2 = "https://www.ledevoir.com/opinion/chroniques/578376/un-message-trop-confus"
url2 = url2.replace("https://www.ledevoir.com/","") # Il faut lui appliquer la méthode .replace() pour qu'elle ait la même structure que la variable url
url2[:url2.find("/")]

'opinion'

Voyez: même si «monde» et «opinion» n'ont pas le même nombre de caractères, on peut les repérer avec la méthode ```.find()```.


Appliquons-la à nos variables ```url``` et ```url2``` pour que vous en voyez le résultat:

In [54]:
url[url.rfind("/")+1:]

'mieux-vaut-prevenir-que-guerir-dit-l-oms'

In [55]:
url2[url2.rfind("/")+1:]

'un-message-trop-confus'

C'est ainsi qu'on peut extraire la fin d'un URL. Vous avez remarqué que j'ai ajouté «+1» à la méthode ```.rfind()```. On peut en effet faire cela puisque le résultat de cette méthode est un numéro d'index et qu'un numéro d'index est nombre entier sur lequel on peut faire des calculs.

<h4 style="background:cyan;text-align:center;padding:10px">Listes</h4>

Les listes sont le type de variable avec lequel vous allez le plus travailler.

Jusqu'à maintenant, on a vu des variables qui ne pouvaient contenir qu'une seule valeur à la fois. Les listes sont des variables qui peuvent contenir plusieurs valeurs. On peut même y ajouter ou retrancher des valeurs.

Les valeurs, dans ces listes, sont toujours incluses entre crochets (```[]```) séparées par des virgules. Voici un exemple:

In [56]:
pouet = [34,78,345,99,0,1,353,25,525,25,66,22,678,1090]

La variable ```pouet``` contient une série de nombre entiers.

In [57]:
pouet

[34, 78, 345, 99, 0, 1, 353, 25, 525, 25, 66, 22, 678, 1090]

Son type est, vous l'aurez deviné:

In [58]:
type(pouet)

list

On peut mettre du texte dans des listes.

In [59]:
fleurs = ["Tulipe","Rose","Orchidée"]

In [60]:
fleurs

['Tulipe', 'Rose', 'Orchidée']

Tous les types de variables qu'on a vu peuvent être inclus dans des listes. Même des listes peuvent être incluses dans des listes! Et on peut également mêler différents types de variables dans une même liste.

In [61]:
wtf = [99,5.5,"Bonjour toi!!!",True,None,[3,8,25,49]]

In [62]:
wtf

[99, 5.5, 'Bonjour toi!!!', True, None, [3, 8, 25, 49]]

<h5 style="background:beige;text-align:center;padding:10px">Fonctions et méthodes relatives aux listes</h5>

La fonction ```range()``` vous permet de générer des nombres dans une étendue donnée. Il faut cependant l'insérer dans une autre fonction, la fonction ```list()``` pour que cette étendue soit transformée en une liste.

Ainsi, la variable ```tintin```, ci-dessous, contient tous les nombres de 7 à 77. Vous aurez remarqué que, comme avec les étendues qu'on a vu ci-dessus pour extraire des portions de texte, la fin de l'étendue n'est pas incluse.

In [63]:
tintin = list(range(7,78))
tintin

[7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77]

Par défaut, la fonction ```range()``` génère des nombres qui se suivent. Mais elle peut contenir un troisième argument qui précise une valeur d'incrément différente. Ainsi, le code ci-dessous génère des nombres par quatre, ce qui fait que la variable ```olympiques``` contient en fait la liste de toutes les années où ont (ou auraient dû être) présentés des jeux olympiques de l'ère moderne.

In [64]:
olympiques = list(range(1896,2024,4))
olympiques

[1896,
 1900,
 1904,
 1908,
 1912,
 1916,
 1920,
 1924,
 1928,
 1932,
 1936,
 1940,
 1944,
 1948,
 1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020]

Les fonctions ```min()``` et ```max()``` vous retournent les plus petites et les plus grandes valeurs d'une liste donnée. Cela fonctionne aussi avec du texte (dans ce cas, c'est l'ordre alphabétique qui déterminera les valeurs minimale et maximale).

In [65]:
min(olympiques), min(fleurs)

(1896, 'Orchidée')

In [66]:
max(tintin), max(fleurs)

(77, 'Tulipe')

On peut ajouter des éléments à une liste grâce à la méthode ```.append()``` qui signifie adjoindre.

Par exemple, ci-dessous, on ajoute le nom d'une autre fleur à notre variables ```fleurs```:

In [67]:
fleurs.append("Marguerite")

En affichant le contenu de la variable, on constate en effet qu'elle contient désormais quatre éléments.

In [68]:
fleurs

['Tulipe', 'Rose', 'Orchidée', 'Marguerite']

Comme avec du texte, il est possible de demander la taille d'une liste avec la fonction ```len()```. Elle ne nous retournera pas le nombre de caractères contenus dans la liste, mais seulement le nombre d'éléments.

In [69]:
len(fleurs)

4

Je vous présente une dernière méthode. Elle s'applique aux variables de type texte. Mais je vous en parle ici parce que son résultat est une liste.

Il s'agit de la méthode ```.split()```. Elle permet de briser un texte en fonction d'un caractère donné, ou d'une chaîne de caractères donnée.

Par exemple, si on prend notre variable ```url```, on peut la briser en fonction de la barre oblique («/») pour produire une liste dont les éléments sont composés du texte se trouvant de part et d'autre de toutes les barres obliques contenues dans ```url```.

Pour rappel, voici le contenu de la variable:

In [70]:
url

'monde/578461/mieux-vaut-prevenir-que-guerir-dit-l-oms'

Y appliquer la méthode ```.split()``` avec l'argument ```"/"``` va briser notre variable en trois éléments distincts.

In [71]:
url.split("/")

['monde', '578461', 'mieux-vaut-prevenir-que-guerir-dit-l-oms']

C'est ainsi que si on souhaite accéder seulement à la section («monde»), seulement au code d'article («578461») ou seulement au titre de l'article, on peut utiliser du code comme celui-ci:

In [72]:
url.split("/")[0]

'monde'

In [73]:
url.split("/")[1]

'578461'

In [74]:
url.split("/")[2]

'mieux-vaut-prevenir-que-guerir-dit-l-oms'

Ou encore, on peut mettre le résultat du ```.split()``` dans une autre variable et accéder à ses différents éléments de la façon suivante:

In [75]:
detailsArticle = url.split("/")
detailsArticle[2]

'mieux-vaut-prevenir-que-guerir-dit-l-oms'

<h5 style="background:beige;text-align:center;padding:10px">Notion d'index avec les listes</h5>

La notion d'**index** qu'on a vue ci-dessus avec les variables de type texte s'applique également aux variables de type liste.

Pour extraire le premier élément d'une liste, par exemple, c'est l'index ```0``` qu'il faut utiliser.

In [76]:
fleurs[0]

'Tulipe'

Les étendues fontionnent de la même façon.

Et, en passant, on peut mettre ces étendues dans d'autres variables (quelque chose qu'il est aussi possible de faire avec du texte).

In [77]:
boomers = tintin[-17:]
boomers # La variable boomers est une autre liste, créée à partir de la liste tintin

[61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77]

Il faut aussi savoir qu'on peut enchaîner ces appels d'index. Par exemple, pour accéder à un élément qui se trouve dans une liste qui est elle-même un élément inséré dans une autre liste. Vous souvenez de la variable ```wtf```?

In [78]:
wtf

[99, 5.5, 'Bonjour toi!!!', True, None, [3, 8, 25, 49]]

Son dernier élément est une liste. On y accéderait en utilisant l'index -1.
Pour y extraire le 3e élément de cette liste, on utiliserait ensuite l'index 2.
Mais pour y aller directement, on peut enchaîner ces deux appels d'index de la façon suivante, et ça nous retourne le nombre entier 25, qui est bel et bien le 3e élément de la liste qui est le dernier élément de la liste ```wtf```.

In [79]:
wtf[-1][2]

25

<h4 style="background:cyan;text-align:center;padding:10px">Dictionnaires</h4>

Le dernier type de variable dont je veux vous parler est peut-être le plus complexe. Il s'agit des **dictionnaires**.

Les dictionnaires sont comme des listes qui nous donnent plus d'information. On les reconnaît parce que tous les éléments y sont inclus entre des accolades (```{}```).

Tous les éléments, comme dans le cas des listes, y sont séparés par des virgules.

Chaque élément, cependant, est composé de deux parties:

- une clé, qui décrit l'élément
- une valeur, qui contient l'élément proprement dit

Les paires **clé:valeur** sont toujours séparées par deux-points (```:```)

Voici un exemple. La variable ```jo``` est un dictionnaire.

In [80]:
jo = {"Année":1896,"Ville":"Athènes","Pays participants":["France","Grèce","Empire Ottoman","États-Unis"]}

Cela peut ressembler à du charabia, mais quand on s'y arrête et qu'on lit la variable ```jo```, on constate rapidement qu'elle contient trois éléments:

1. la clé du premier est «Année» et sa valeur est le nombre 1896.
* la clé du deuxième est «Ville» et sa valeur est le texte «Athènes».
* la clé du troisième est «Pays participants» et sa valeur est une liste (incomplète) des pays qui ont participé à ces jeux.

En passant, le nom du type de ces variable est abrégé à ```dict```.

In [81]:
type(jo)

dict

Si, dans le cadre de vos recherches, vous avez à recueillir des données dans le web, dans des réseaux sociaux, ou ailleurs, il est fort probable que vous rencontriez des dictionnaires. Il est ainsi utile d'en reconnaître la structure pour mieux les lire et en extraire les données qui vous intéressent.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Bixi_logo.svg/320px-Bixi_logo.svg.png">

Un exemple: l'état des stations du réseau Bixi est présenté dans [cette page de données ouvertes](https://api-core.bixi.com/gbfs/fr/station_status.json). Il s'agit d'un fichier [JSON](https://www.json.org/json-fr.html) dont la structure est identique à celle d'un dictionnaire en python.

Si vous allez la consulter, vous verrez qu'elle contient, à la base, elle aussi, trois éléments:

<ol>
    <li>la clé du premier est «last_updated» et sa valeur est un nombre qui est, en fait, une «époque» en format Unix que vous pouvez convertir en date grâce à [cet outil en ligne](https://www.epochconverter.com/).</li>
    <li>la clé du deuxième est «ttl» et sa valeur un nombre quelconque (j'ignore ce que ça veut dire)</li>
    <li>et la clé du troisième est «data» et sa valeur est, tiens donc, un autre dictionnaire qui ne contient qu'une paire clé:valeur:</li>
    <ul>
        <li>la clé est «stations» et la valeur est une grande liste des 617 stations Bixi à Montréal:</li>
        <ul>
            <li>chaque élément de cette liste est un dictionnaire qui contient 11 éléments ou paires de clé:valeur donnant des infos sur le nombre de vélos ou d'ancrages disponibles.</li>
        </ul>
    </ul>
</ol>

On va examiner au prochain cours comment extraire des données à partir d'un dictionnaire.

<h3 style="background:pink;text-align:center;padding:10px">Boucles</h3>

<h4 style="background:cyan;text-align:center;padding:10px">Boucles ```for```</h4>

Tout l'intérêt de programmer tient dans la possibilité de traiter un grand volume d'information et d'éviter de faire manuellement des tâches répétitives. La façon d'automatiser ces tâches répétitives est de les faire à l'aide d'une boucle.

En python, la syntaxe des boucles peut avoir la forme suivante:

<code>**for** variable **in** liste:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&lt;On fait quelque chose avec la variable&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;On peut inclure d'autre code aussi&gt;*
</code>

Vous remarquerez que la première ligne, dans laquelle on déclare la boucle avec l'expression ```for```, se termine par un deux-points (```:```). Ce deux points est toujours requis.

Vous remarquerez aussi que les deux lignes qui suivent sont décalées de quelques caractères (ou d'un ```<tab>```) vers la droite. On appelle ce décalage l'**indentation**. Cette indentation est importante. Tout ce qui est indenté sera exécuté par la boucle. Si on souhaite quitter la boucle et écrire du code qui ne sera pas exécuté par celle-ci, il suffit de le «désintenter», de le décaler d'un cran vers la gauche.

C'est avec les boucles qu'on comprend tout l'intérêt de mettre des données dans des listes. Une boucle va vous permettre de traiter, l'un après l'autre, chacun des éléments de cette liste.

Dans l'exemple ci-dessous, on va écrire le même texte avec les éléments de notre liste ```fleurs```.

In [82]:
for fleur in fleurs:
    print("J'adore les {}s".format(fleur.lower()))

J'adore les tulipes
J'adore les roses
J'adore les orchidées
J'adore les marguerites


Dans l'exemple ci-dessus, la boucle ```for``` prend chacun des éléments de la variable ```fleurs```.

À chaque itération, la boucle place l'élément où elle est rendue dans la variable ```fleur``` (au singulier). J'aime bien donner des noms explicites à mes variables. C'est un bon exemple, ici. J'ai pris l'habitude de donner à mes variables de type liste, qui contiennent plusieurs éléments, des noms au pluriel, et aux variables qui suivent l'expression ```for``` des noms au singulier.

Au passage, elle la transforme en minuscules avec la méthode ```.lower()``` et l'insère dans un texte avec la méthode ```.format()```.

<p style="text-align:center">***</p>

Nous allons maintenant travailler avec une liste qui était incluse dans un fichier texte que je vous ai transféré par Zoom.

In [83]:
films = [["À la croisée des chemins","Paul Guèvremont","1943"],
["Le Père Chopin","Fedor Ozep","1945"],
["La Forteresse","Fedor Ozep","1947"],
["Whispering City","Fedor Ozep","1947"],
["On ne triche pas avec la vie","René Delacroix et Paul Vandenberghe","1949"],
["Le Curé de village","Paul Gury","1949"],
["Le Gros Bill","Jean-Yves Bigras et René Delacroix","1949"],
["Un homme et son péché","Paul Gury","1949"],
["Les Lumières de ma ville","Jean-Yves Bigras","1950"],
["L'Inconnue de Montréal","Jean Devaivre","1950"],
["Séraphin","Paul Gury","1950"],
["Étienne Brûlé gibier de potence","Melburn E. Turner","1952"],
["La Petite Aurore, l'enfant martyre","Jean-Yves Bigras","1952"],
["Le Rossignol et les Cloches","René Delacroix","1952"],
["Cœur de maman","René Delacroix","1953"],
["Tit-Coq","Gratien Gélinas et René Delacroix","1953"],
["L'Esprit du mal","Jean-Yves Bigras","1954"],
["Le Village enchanté","Marcel et Réal Racicot","1956"],
["Le Survenant","Un collectif de réalisateurs","1957"],
["Les Mains nettes","Claude Jutra","1958"],
["Les Brûlés","Bernard Devlin","1959"],
["Accade in Canada","Luigi Petrucci","1962"],
["Seul ou avec d'autres","Denys Arcand avec Denis Héroux et Stéphane Venne","1962"],
["À tout prendre","Claude Jutra","1963"],
["Amanita Pestilens","René Bonnière","1963"],
["Drylanders (Un autre pays)","Donald Haldane","1963"],
["Le Chat dans le sac","Gilles Groulx","1964"],
["La Fleur de l'âge, ou Les adolescentes","Un collectif de réalisateurs","1964"],
["Jusqu'au cou","Denis Héroux","1964"],
["Nobody Waved Good-Bye","Don Owen","1964"],
["La Terre à boire","Jean-Paul Bernier","1964"],
["Trouble-fête","Pierre Patry","1964"],
["Astataïon ou le Festin des morts","Fernand Dansereau","1965"],
["Caïn","Pierre Patry","1965"],
["La Corde au cou","Pierre Patry","1965"],
["Le Coup de grâce","Jean Cayrol et Claude Durand","1965"],
["Pas de vacances pour les idoles","Denis Héroux","1965"],
["Le Révolutionnaire","Jean Pierre Lefebvre","1965"],
["La Vie heureuse de Léopold Z.","Gilles Carle","1965"],
["Carnaval en chute libre","Guy Bouchard","1966"],
["La Douzième heure","Jean Martimbeau","1966"],
["Footsteps in the Snow (Des pas sur la neige)","Martin Green","1966"],
["Yul 871","Jacques Godbout","1966"],
["Entre la mer et l'eau douce","Michel Brault","1967"],
["Il ne faut pas mourir pour ça","Jean Pierre Lefebvre","1967"],
["Manette : la folle et les dieux de carton","Camil Adam","1967"],
["C'est pas la faute à Jacques Cartier","Georges Dufaux et Clément Perron","1968"],
["Façade","Larry Kent","1968"],
["Isabel","Paul Almond","1968"],
["Las Joyas del diablo (Le diable aime les bijoux)","José Maria Elorrieta","1968"],
["Kid Sentiment","Jacques Godbout","1968"],
["Patricia et Jean-Baptiste","Jean Pierre Lefebvre","1968"],
["Poussière sur la ville","Arthur Lamothe","1968"],
["T-bone Steak dans... les mangeuses d'hommes","Gilles Marchand et Hugues Tremblay","1968"],
["Le Viol d'une jeune fille douce","Gilles Carle","1968"],
["La Chambre blanche","Jean Pierre Lefebvre","1969"],
["Danger pour la société","Jean Martimbeau","1969"],
["Délivrez-nous du mal","Jean-Claude Lord","1969"],
["Don't Let the Angels Fall (Seuls les enfants étaient présents)","George Kaczender","1969"],
["Le Grand Rock","Raymond Garceau","1969"],
["Jusqu'au cœur","Jean Pierre Lefebvre","1969"],
["Mon amie Pierrette","Jean Pierre Lefebvre","1969"],
["Où êtes-vous donc ?","Gilles Groulx","1969"],
["Le Soleil des autres","Jean Faucher","1969"],
["Valérie","Denis Héroux","1969"],
["Act of the Heart","Paul Almond","1970"],
["Ainsi soient-ils","Yvan Patry","1970"],
["L'Amour humain","Denis Héroux","1970"],
["Deux femmes en or","Claude Fournier","1970"],
["Entre tu et vous","Gilles Groulx","1970"],
["L'Initiation","Denis Héroux","1970"],
["Love in a 4 Letter World","John Sone","1970"],
["On est loin du soleil","Jacques Leduc","1970"],
["Pile ou face","Roger Fournier","1970"],
["Q-bec my love","Jean Pierre Lefebvre","1970"],
["Quand hurlent les loups","André Lafferrere","1970"],
["Red","Gilles Carle","1970"],
["St-Denis dans le temps...","Marcel Carrière","1970"],
["Vive la France","Raymond Garceau","1970"],
["Wow","Claude Jutra","1970"],
["7 fois… (par jour)","Denis Héroux","1971"],
["Après-ski","Roger Cardinal","1971"],
["Les Chats bottés","Claude Fournier","1971"],
["Corps et âme","Michel Audy","1971"],
["L'Explosion","Marc Simenon","1971"],
["Finalement...","Richard Martin","1971"],
["Fleur bleue","Larry Kent","1971"],
["Le Grand film ordinaire","Roger Frappier","1971"],
["IXE-13","Jacques Godbout","1971"],
["Jean-François Xavier de...","Michel Audy","1971"],
["Les Mâles","Gilles Carle","1971"],
["Le Martien de Noël","Bernard Gosselin","1971"],
["Les Maudits sauvages","Jean Pierre Lefebvre","1971"],
["Mon enfance à Montréal","Jean Chabot","1971"],
["Mon œil","Jean Pierre Lefebvre","1971"],
["Mon oncle Antoine","Claude Jutra","1971"],
["Question de vie","André Théberge","1971"],
["Le Retour de l'Immaculée Conception","André Forcier","1971"],
["Stop","Jean Beaudin","1971"],
["Tiens-toi bien après les oreilles à Papa...","Jean Bissonnette","1971"],
["Ty-Peupe","Fernand Bélanger","1971"],
["L'Apparition","Roger Cardinal","1972"],
["Les Colombes","Jean-Claude Lord","1972"],
["Le diable est parmi nous","Jean Beaudin","1972"],
["Et du fils","Raymond Garceau","1972"],
["L'exil","Thomas Vamos","1972"],
["Le Grand Sabordage","Alain Périsson","1972"],
["Isis au 8","Alain Chartrand","1972"],
["Journey","Paul Almond","1972"],
["La Maudite Galette","Denys Arcand","1972"],
["Montréal blues","Pascal Gélinas","1972"],
["Le p'tit vient vite","Louis-Georges Carrier","1972"],
["Pas de jeu sans soleil","Claude Bérubé","1972"],
["Quelques arpents de neige","Denis Héroux","1972"],
["Les Smattes","Jean-Claude Labrecque","1972"],
["Le Temps d'une chasse","Francis Mankiewicz","1972"],
["La Tête au neutre","Jean Gagné","1972"],
["Un enfant comme les autres","Denis Héroux","1972"],
["La Vie rêvée","Mireille Dansereau","1972"],
["La Vraie nature de Bernadette","Gilles Carle","1972"],
["Ah ! Si mon moine voulait...","Claude Pierson","1973"],
["Les Allées de la terre","André Théberge","1973"],
["La Conquête","Jean Gagné","1973"],
["Les Corps célestes","Gilles Carle","1973"],
["Les Dernières fiançailles","Jean Pierre Lefebvre","1973"],
["Il était une fois dans l'Est","André Brassard","1973"],
["J'ai mon voyage!","Denis Héroux","1973"],
["Kamouraska","Claude Jutra","1973"],
["Keep it in the Family","Larry Kent","1973"],
["La Maîtresse","Anton Van de Water","1973"],
["La Mort d'un bûcheron","Gilles Carle","1973"],
["Mourir pour vivre","Franco Vigilante","1973"],
["The Neptune Factor: An Undersea Odyssey","Daniel Petrie","1973"],
["Noël et Juliette","Michel Bouchard","1973"],
["O.K.... Laliberté","Marcel Carrière","1973"],
["On n'engraisse pas les cochons à l'eau claire","Jean Pierre Lefebvre","1973"],
["The Rainbow Boys","Gerald Potterton","1973"],
["Réjeanne Padovani","Denys Arcand","1973"],
["Sensations","Robert Séguin","1973"],
["A Star is Lost!","John Howe","1973"],
["Taureau","Clément Perron","1973"],
["Tendresse ordinaire","Jacques Leduc","1973"],
["Tu brûles... tu brûles...","Jean-Guy Noël","1973"],
["U-Turn","George Kaczender","1973"],
["Ultimatum","Jean Pierre Lefebvre","1973"],
["Y a toujours moyen de moyenner!","Denis Héroux","1973"],
["Alien Thunder","Claude Fournier","1974"],
["The Apprenticeship of Duddy Kravitz","Ted Kotcheff","1974"],
["Au boutt'","Roger Laliberté","1974"],
["Les Aventures d'une jeune veuve","Roger Fournier","1974"],
["Bar Salon","André Forcier","1974"],
["Les Beaux dimanches","Richard Martin","1974"],
["Bingo","Jean-Claude Lord","1974"],
["Bulldozer","Pierre Harel","1974"],
["Les Deux pieds dans la même bottine","Pierre Rose","1974"],
["La Gammick","Jacques Godbout","1974"],
["Guitare","Richard Lavoie","1974"],
["Je t'aime","Pierre Duceppe","1974"],
["Montreal Main","Frank Vitale","1974"],
["Ô ou l'invisible enfant","Raôul Duguay","1974"],
["Les Ordres","Michel Brault","1974"],
["Le Plumard en folie","Jacques Lem","1974"],
["La Pomme, la queue... et les pépins!","Claude Fournier","1974"],
["Running Time","Mort Ransen","1974"],
["Why Rock the Boat?","John Howe","1974"],
["Y'a pas d'mal à se faire du bien","Claude Mulot","1974"],
["L'amour blessé","Jean Pierre Lefebvre","1975"],
["Candice Candy","Pierre Unia","1975"],
["Cold Journey","Martin Defalco","1975"],
["Eliza's Horoscope","Gordon Sheppard","1975"],
["Gina","Denys Arcand","1975"],
["The Heatwave Lasted Four Days","Douglas Jackson","1975"],
["L'île jaune","Jean Cousineau","1975"],
["Lies My Father Told Me","Ján Kádar","1975"],
["M'en revenant par les épinettes","François Brault","1975"],
["Mustang","Marcel Lefebvre","1975"],
["Partis pour la gloire","Clément Perron","1975"],
["Pour le meilleur et pour le pire","Claude Jutra","1975"],
["Pousse mais pousse égal","Denis Héroux","1975"],
["Shivers","David Cronenberg","1975"],
["Le temps de l'avant","Anne Claire Poirier","1975"],
["La tête de Normande St-Onge","Gilles Carle","1975"],
["Tout feu, tout femme","Gilles Richer","1975"],
["Une nuit en Amérique","Jean Chabot","1975"],
["Les vautours","Jean-Claude Labrecque","1975"],
["L'absence","Brigitte Sauriol","1976"],
["Beat","André Blanchard","1976"],
["Born for Hell","Denis Héroux","1976"],
["Chanson pour Julie","Jacques Vallée","1976"],
["Contebleu","Yves Angrignon","1976"],
["Death Weekend","William Fruet","1976"],
["La fleur aux dents","Thomas Vamos","1976"],
["J.A. Martin photographe","Jean Beaudin","1976"],
["Je suis loin de toi mignonne","Claude Fournier","1976"],
["Jos Carbone","Hugues Tremblay","1976"],
["The Little Girl Who Lives Down the Lane","Nicolas Gessner","1976"],
["Parlez-nous d'amour","Jean-Claude Lord","1976"],
["La piastre","Alain Chartrand","1976"],
["Simple histoire d'amours","Fernand Dansereau","1976"],
["Ti-Cul Tougas","Jean-Guy Noël","1976"],
["L'ange et la femme","Gilles Carle","1977"],
["Cathy's Curse","Eddy Matalon","1977"],
["L'eau chaude, l'eau frette","André Forcier","1977"],
["Full Circle","Richard Loncraine","1977"],
["Ilsa the Tigress of Siberia","Jean Lafleur","1977"],
["La menace","Alain Corneau","1977"],
["One Man","Robin Spry","1977"],
["La p'tite violence","Hélène Girard","1977"],
["Panique","Jean-Claude Lord","1977"],
["Rabid","David Cronenberg","1977"],
["Rituals","Peter Carter","1977"],
["Le soleil se lève en retard","André Brassard","1977"],
["Ti-Mine, Bernie pis la gang…","Marcel Carrière","1977"],
["Le vieux pays où Rimbaud est mort","Jean Pierre Lefebvre","1977"],
["L'ange gardien","Jacques Fournier","1978"],
["Blackout","Eddy Matalon","1978"],
["City on Fire","Alvin Rakoff","1978"],
["Comme les six doigts de la main","André Mélançon","1978"],
["Drying Up the Streets","Robin Spry","1978"],
["L'homme en colère","Claude Pinoteau","1978"],
["In Praise of Older Women","George Kaczender","1978"],
["Jacob Two-Two Meets the Hooded Fang","Theodore J. Flicker","1978"],
["Les liens de sang","Claude Chabrol","1978"],
["Tomorrow Never Comes","Peter Collinson","1978"],
["Un grand logement","Mario Bolduc et Marie-Ginette Guay","1978"],
["Une amie d'enfance","Francis Mankiewicz","1978"],
["Violette Nozière","Claude Chabrol","1978"],
["À nous deux","Claude Lelouch","1979"],
["L'affaire Coffin","Jean-Claude Labrecque","1979"],
["L'arrache-cœur","Mireille Dansereau","1979"],
["Au revoir… à lundi","Maurice Dugowson","1979"],
["Avoir 16 ans","Jean Pierre Lefebvre","1979"],
["La belle apparence","Denyse Benoît","1979"],
["The Brood","David Cronenberg","1979"],
["Caro papa","Dino Risi","1979"],
["Les célébrations","Yves Simoneau","1979"],
["Le château de cartes","François Labonté","1979"],
["Cordélia","Jean Beaudin","1979"],
["Éclair au chocolat","Jean-Claude Lord","1979"],
["Fuir","Hélène Girard","1979"],
["Girls","Just Jaeckin","1979"],
["L'hiver bleu (Abitibi 1978)","André Blanchard","1979"],
["La maladie c'est les compagnies","Richard Boutet","1979"],
["A Man Called Intrepid","Peter Carter","1979"],
["Mourir à tue-tête","Anne Claire Poirier","1979"],
["Vie d'ange","Pierre Harel","1979"],
["Agency","George Kaczender","1980"],
["Atlantic City, U.S.A.","Louis Malle","1980"],
["Les bons débarras","Francis Mankiewicz","1980"],
["Ça peut pas être l'hiver on n'a même pas eu d'été","Louise Carré","1980"],
["Le chef se déniaise","Jean Luret","1980"],
["Contrecœur","Jean-Guy Noël","1980"],
["La cuisine rouge","Paule Baillargeon","1980"],
["Fantastica","Gilles Carle","1980"],
["Final Assignment","Paul Almond","1980"],
["Les grands enfants","Paul Tana","1980"],
["Hog Wild","Les Rose","1980"],
["L'homme à tout faire","Micheline Lanctôt","1980"],
["Hot Dogs","Claude Fournier","1980"],
["The Lucky Star","Max Fischer","1980"],
["Pinball Summer","George Mihalka","1980"],
["Strass café","Léa Pool","1980"],
["Suzanne","Robin Spry","1980"],
["Terror Train","Roger Spottiswoode","1980"],
["Thetford au milieu de notre vie","Iolande Cadrin-Rossignol et Fernand Dansereau","1980"],
["Les beaux souvenirs","Francis Mankiewicz","1981"],
["Black Mirror","Pierre-Alain Jolivet","1981"],
["Deux super dingues","Claude Castravelli","1981"],
["The Funny Farm","Ron Clark","1981"],
["Gas","Les Rose","1981"],
["La guerre du feu","Jean-Jacques Annaud","1981"],
["Happy Birthday to Me","J. Lee Thompson","1981"],
["Hard Feelings","Daryl Duke","1981"],
["Heartaches","Donald Shebib","1981"],
["Hot Touch","Roger Vadim","1981"],
["My Bloody Valentine","George Mihalka","1981"],
["Les Plouffe","Gilles Carle","1981"],
["Salut! J.W.","Ian Ireland","1981"],
["Le shift de nuit","Mario Bolduc","1981"],
["Ups & Downs","Paul Almond","1981"],
["Yesterday","Larry Kent","1981"],
["Your Ticket is No Longer Valid","George Kaczender","1981"],
["Cross Country","Paul Lynch","1982"],
["Doux aveux","Fernand Dansereau","1982"],
["Les fleurs sauvages","Jean Pierre Lefebvre","1982"],
["Le futur intérieur","Jean Chabot","1982"],
["Killing 'em Softly","Max Fischer","1982"],
["Larose, Pierrot et la Luce","Claude Gagnon","1982"],
["Luc ou La part des choses","Michel Audy","1982"],
["Paradise","Stuart Gilliard","1982"],
["La quarantaine","Anne-Claire Poirier","1982"],
["Scandale","George Mihalka","1982"],
["Une journée en taxi","Robert Ménard","1982"],
["Visiting Hours","Jean-Claude Lord","1982"],
["Les yeux rouges ou Les vérités accidentelles","Yves Simoneau","1982"],
["Au clair de la lune","André Forcier","1983"],
["Au pays de Zom","Gilles Groulx","1983"],
["Bonheur d'occasion","Claude Fournier","1983"],
["Lucien Brouillard","Bruno Carrière","1983"],
["Maria Chapdelaine","Gilles Carle","1983"],
["Porky's 2: The Next Day","Bob Clark","1983"],
["Rien qu'un jeu","Brigitte Sauriol","1983"],
["Le ruffian","José Giovanni","1983"],
["Snapshot","Abderahmane Mazouz","1983"],
["Videodrome","David Cronenberg","1983"],
["The Wars","Robin Phillips","1983"],
["Les Années de rêves","Jean-Claude Labrecque","1984"],
["The Bay Boy","Daniel Petrie","1984"],
["La couleur encerclée","Jean Gagné, Serge Gagné","1984"],
["Le crime d'Ovide Plouffe","Denys Arcand","1984"],
["Evil Judgment","Claude Castravelli","1984"],
["La femme de l'hôtel","Léa Pool","1984"],
["La Guerre des tuques","André Melançon","1984"],
["Hey Babe!","Rafal Zielinski","1984"],
["The Hotel New Hampshire","Tony Richardson","1984"],
["Jacques et Novembre","Jean Beaudry","1984"],
["Le jour « S... »","Jean Pierre Lefebvre","1984"],
["Louisiana","Philippe de Broca","1984"],
["Mario","Jean Beaudin","1984"],
["The Masculine Mystique","John N. Smith, Giles Walker","1984"],
["Memoirs","Bashar Shbib","1984"],
["Mother's Meat Freuds Flesh","Demetri Demetrios","1984"],
["Paroles et musiques","Élie Chouraqui","1984"],
["Perfect Timing","René Bonnière","1984"],
["Le sang des autres","Claude Chabrol","1984"],
["Sonatine","Micheline Lanctôt","1984"],
["The Surrogate","Don Carmody","1984"],
["90 Days","Giles Walker","1985"],
["L'adolescente sucre d'amour","Jocelyne Saab","1985"],
["Adramélech","Pierre Grégoire","1985"],
["Bayo","Mort Ransen","1985"],
["The Blue Man","George Mihalka","1985"],
["Caffè Italia Montréal","Paul Tana","1985"],
["Celui qui voit les heures","Pierre Goupil","1985"],
["La dame en couleurs","Claude Jutra","1985"],
["Le dernier glacier","Roger Frappier, Jacques Leduc","1985"],
["Elvis Gratton : Le king des kings","Pierre Falardeau","1985"],
["The Gunrunner","Nardo Castillo","1985"],
["Instantanés","Michel Juliani","1985"],
["Joshua Then and Now","Ted Kotcheff","1985"],
["Junior","Jim Hanley","1985"],
["Lune de miel","Patrick Jamain","1985"],
["Le matou","Jean Beaudin","1985"],
["Medium blues","Michel Préfontaine","1985"],
["Night Magic","Lewis Furey","1985"],
["Opération beurre de pinottes","Michael Rubbo","1985"],
["Québec, opération Lambda","Marc Degryse","1985"],
["Visage pâle","Claude Gagnon","1985"],
["Anne Trister","Léa Pool","1986"],
["Bach et Bottine","André Melançon","1986"],
["The Boy in Blue","Charles Jarrott","1986"],
["Cat Squad","William Freidkin","1986"],
["Contes des mille et un jours","Iolande Cadrin-Rossignol","1986"],
["Deaf & Mute","Hunt Hoe","1986"],
["Le Déclin de l'empire américain","Denys Arcand","1986"],
["Le dernier havre","Denyse Benoit","1986"],
["Équinoxe","Arthur Lamothe","1986"],
["Evixion","Bashar Shbib","1986"],
["The First Killing Frost","Roland Hallé","1986"],
["Exit","Robert Ménard","1986"],
["Les fous de bassan","Yves Simoneau","1986"],
["La guêpe","Gilles Carle","1986"],
["Henri","François Labonté","1986"],
["L'homme renversé","Yves Dion","1986"],
["Meatballs 3","George Mendeluk","1986"],
["The Morning Man","Danièle J Suissa","1986"],
["Overnight","Jack Darcus","1986"],
["Pouvoir intime","Yves Simoneau","1986"],
["Qui a tiré sur nos histoires d'amour?","Louise Carré","1986"],
["Sauve-toi Lola","Michel Drach","1986"],
["Sitting in Limbo","John N. Smith","1986"],
["Toby McTeague","Jean-Claude Lord","1986"],
["À l'automne de la vie","Yvan Chouinard","1987"],
["The Great Land of Small","Vojtech Jasny","1987"],
["Le frère André","Jean-Claude Labrecque","1987"],
["Grelots rouges sanglots bleus","Pierre Harel","1987"],
["La Guerre oubliée","Richard Boutet","1987"],
["Hitting Home","Robin Spry","1987"],
["L'Île","François Leterrier","1987"],
["Le Jeune Magicien","Waldemar Dziki","1987"],
["Keeping Track","Robin Spry","1987"],
["The Kid Brother ou Kenny","Claude Gagnon","1987"],
["The Last Straw","Giles Walker","1987"],
["La ligne de chaleur","Hubert-Yves Rose","1987"],
["Marie s'en va-t-en ville","Marquise Lepage","1987"],
["Les roses de Matmata","José Pinheiro","1987"],
["Seductio","Bashar Shbib","1987"],
["Le sourd dans la ville","Mireille Dansereau","1987"],
["Tinamer","Jean-Guy Noël","1987"],
["Train of Dreams","John N. Smith","1987"],
["Tristesse, modèle réduit","Robert Morin","1987"],
["Un zoo la nuit","Jean-Claude Lauzon","1987"],
["À corps perdu","Léa Pool","1988"],
["La boîte à soleil","Jean Pierre Lefebvre","1988"],
["La bottega del orefice","Michael Anderson","1988"],
["Clair-obscur","Bashar Shbib","1988"],
["Eva Guerrillera","Jacqueline Levitin","1988"],
["Family Reunion","Dick Sarin","1988"],
["Gaspard et fils","François Labonté","1988"],
["La Grenouille et la Baleine","Jean-Claude Lord","1988"],
["Horses in Winter","Rick Raxlen","1988"],
["Kalamazoo","André Forcier","1988"],
["Moonlight Flight","Jim Kaufman","1988"],
["La nuit avec Hortense","Jean Chabot","1988"],
["Oh! Oh! Satan!","André Farwagi","1988"],
["La peau et les os","Johanne Prégent","1988"],
["Les Portes tournantes","Francis Mankiewicz","1988"],
["Salut Victor","Anne Claire Poirier","1988"],
["Something About Love","Tom Berry","1988"],
["Les Tisserands du pouvoir","Claude Fournier","1988"],
["Tommy Tricker and the Stamp Traveller","Michael Rubbo","1988"],
["L'Air de rien","Mary Jimenez","1989"],
["The Amityville Curse","Tom Berry","1989"],
["Bye bye Chaperon rouge","Márta Mészáros","1989"],
["Cher frangin","Gérard Mordillat","1989"],
["Comment faire l'amour avec un nègre sans se fatiguer","Jacques W. Benoît","1989"],
["Cruising Bar","Robert Ménard","1989"],
["Dans le ventre du dragon","Yves Simoneau","1989"],
["Fierro… l'été des secrets","André Melançon","1989"],
["Jésus de Montréal","Denys Arcand","1989"],
["Laura Laur","Brigitte Sauriol","1989"],
["Matinée","Richard Martin","1989"],
["Les matins infidèles","Jean Beaudry, François Bouvier","1989"],
["Mindfield","Jean-Claude Lord","1989"],
["Les Noces de papier","Michel Brault","1989"],
["Off Off Off","Jorge Fajardo","1989"],
["Portion d'éternité","Robert Favreau","1989"],
["La Réception","Robert Morin","1989"],
["La Révolution française : les années terribles","Richard T. Heffron","1989"],
["Short Change","Nicholas Kinsey","1989"],
["Sous les draps, les étoiles","Jean-Pierre Gariepy","1989"],
["T'es belle Jeanne","Robert Ménard","1989"],
["Trois pommes à côté du sommeil","Jacques Leduc","1989"],
["Vent de galerne","Bernard Favre","1989"],
["Welcome to Canada","John N. Smith","1989"],
["Babylone","Manu Bonmariage","1990"],
["Back Stab","Jim Kaufman","1990"],
["Bethune: The Making of a Hero","Phillip Borsos","1990"],
["Breadhead","Carlo Alacchi","1990"],
["A Bullet in the Head","Attila Bertalan","1990"],
["Cargo","François Girard","1990"],
["The Company of Strangers","Cynthia Scott","1990"],
["Cursed","Mychel Arsenault","1990"],
["Dames galantes","Jean-Charles Tacchella","1990"],
["Ding et Dong, le film","Alain Chartrand","1990"],
["Falling Over Backwards","Mort Ransen","1990"],
["La Fille du maquignon","Abderrahmane Mazouz","1990"],
["I'm Happy. You're Happy. We're All Happy. Happy, Happy, Happy.","Verlcrow Ripper","1990"],
["La Liberté d'une statue","Olivier Asselin","1990"],
["Lola Zipper","Ilan Duran Cohen","1990"],
["Manuel : le fils emprunté","François Labonté","1990"],
["Moody Beach","Richard Roy","1990"],
["New York doré","Suzanne Guy","1990"],
["Le Party","Pierre Falardeau","1990"],
["Pas de répit pour Mélanie","Jean Beaudry","1990"],
["Princes in Exile","Giles Walker","1990"],
["Rafales","André Melançon","1990"],
["Remous","Sylvie Van Brabant","1990"],
["Le Royaume ou l'asile","Jean Gagné","1990"],
["The Secret of Nandy","Danièle J Suissa","1990"],
["Simon les nuages","Roger Cantin","1990"],
["Un autre homme","Charles Binamé","1990"],
["Un été après l'autre","Anne-Marie Étienne","1990"],
["Une histoire inventée","André Forcier","1990"],
["Alisée","André Blanchard","1991"],
["Amoureux fou","Robert Ménard","1991"],
["L'annonce faite à Marie","Alain Cuny","1991"],
["L'assassin jouait du trombone","Roger Cantin","1991"],
["La Championne","Elisabeta Bostan","1991"],
["… comme un voleur","Michel Langlois","1991"],
["The Dance Goes On","Paul Almond","1991"],
["Les Danseurs du Mozambique","Philippe Lefebvre","1991"],
["Deadly Surveillance","Paul Ziller","1991"],
["La Demoiselle sauvage","Léa Pool","1991"],
["Le Fabuleux voyage de l'ange","Jean Pierre Lefebvre","1991"],
["The Final Heist","George Mihalka","1991"],
["Lana in Love","Bashar Shbib","1991"],
["Love-moi","Marcel Simard","1991"],
["Montréal vu par…","Un collectif de réalisateurs","1991"],
["Motyli Cas","Bretislav Pojar","1991"],
["Nelligan","Robert Favreau","1991"],
["Pablo qui court","Bernard Bergeron","1991"],
["The Pianist","Claude Gagnon","1991"],
["La Révolution française : les années lumières","Robert Enrico","1991"],
["Scanners 2: The New Order","Christian Duguay","1991"],
["Sous le signe du poisson","Serge Pénard","1991"],
["Un Léger vertige","Diane Poitras","1991"],
["Vincent et moi","Michael Rubbo","1991"],
["Aline","Carole Laganière","1992"],
["L'Automne sauvage","Gabriel Pelletier","1992"],
["Being at Home with Claude","Jean Beaudin","1992"],
["La Bête de foire","Isabelle Hayeur","1992"],
["Call of the Wild","Bjorn Kristen","1992"],
["Canvas","Alain Zaloum","1992"],
["Coyote","Richard Ciupka","1992"],
["A Cry in the Night","Robin Spry","1992"],
["Deadbolt","Douglas Jackson","1992"],
["La Fenêtre","Monique Champagne","1992"],
["Francœur: exit pour nomades","Pierre Bastien","1992"],
["L'Homme de ma vie","Jean-Charles Tacchella","1992"],
["Killer Image","David Winning","1992"],
["El lado oscuro del corazón","Eliseo Subiela","1992"],
["Léolo","Jean-Claude Lauzon","1992"],
["Le Mirage","Jean-Claude Guiguet","1992"],
["La Postière","Gilles Carle","1992"],
["Psychic","George Mihalka","1992"],
["Requiem pour un beau sans-cœur","Robert Morin","1992"],
["La Sarrasine","Paul Tana","1992"],
["Scanners 3: The Takeover","Christian Duguay","1992"],
["Shadow of the Wolf","Jacques Dorfmann, Pierre Magny","1992"],
["Tirelire Combines & Cie","Jean Beaudry","1992"],
["La Vie fantôme","Jacques Leduc","1992"],
["Le Voleur de caméra","Claude Fortin","1992"],
["Les Amoureuses","Johanne Prégent","1993"],
["Armen et Bullik","Allan Cook","1993"],
["Because Why","Arto Paragamian","1993"],
["Cap Tourmente","Michel Langlois","1993"],
["Deux actrices","Micheline Lanctôt","1993"],
["Doublures","Michel Murray","1993"],
["La Florida","George Mihalka","1993"],
["L'Homme sur les quais","Raoul Peck","1993"],
["Love & Human Remains","Denys Arcand","1993"],
["Matusalem","Roger Cantin","1993"],
["Les Mots perdus : un film en quatre saisons","Marcel Simard","1993"],
["The Myth of the Male Orgasm","John Hamilton","1993"],
["The Neighbor","Rodney Gibbons","1993"],
["Pamietnik znaleziony w garbie","Jan Kidawa-Blonski","1993"],
["Les Pots cassés","François Bouvier","1993"],
["Saint-Fortunat, les blues","Daniel St-Laurent","1993"],
["Le Sexe des étoiles","Paule Baillargeon","1993"],
["Tendre guerre","Daniel Morin","1993"],
["Thirty Two Short Films About Glenn Gould","François Girard","1993"],
["La Visite","Jorge Fajardo","1993"],
["C'était le 12 du 12 et Chili avait les blues","Charles Binamé","1994"],
["The Child","George Mihalka","1994"],
["Crack Me Up","Bashar Shbib","1994"],
["Craque la vie !","Jean Beaudin","1994"],
["Draghoula","Basha Shbib","1994"],
["La Fête des rois","Marquise Lepage","1994"],
["Gaïa","Pierre Lang","1994"],
["El jardín del edén","Maria Novaro","1994"],
["Kabloonak","Claude Massot","1994"],
["Le Lac de la lune","Michel Jetté","1994"],
["Louis 19, le roi des ondes","Michel Poulette","1994"],
["Ma sœur, mon amour","Suzy Cohen","1994"],
["Mon amie Max","Michel Brault","1994"],
["Mouvements du désir","Léa Pool","1994"],
["Los Naufragos","Miguel Littin","1994"],
["Octobre","Pierre Falardeau","1994"],
["The Paperboy","Douglas Jackson","1994"],
["Le Retour des aventuriers du timbre perdu","Michael Rubbo","1994"],
["Rêve aveugle","Diane Beaudry","1994"],
["Ride Me","Bashar Shbib","1994"],
["Ruth","François Delisle","1994"],
["Le Secret de Jérôme","Phil Comeau","1994"],
["Stalked","Douglas Jackson","1994"],
["V'la l'cinéma ou le roman de Charles Pathé","Jacques Rouffio","1994"],
["Le Vent du Wyoming","André Forcier","1994"],
["La Vie d'un héros","Micheline Lanctôt","1994"],
["Warriors","Shimon Dotan","1994"],
["Windigo","Robert Morin","1994"],
["Yes sir! Madame…","Robert Morin","1994"],
["Angelo, Frédo et Roméo","Pierre Plante","1995"],
["Le Confessionnal","Robert Lepage","1995"],
["Eldorado","Charles Binamé","1995"],
["L'Enfant d'eau","Robert Ménard","1995"],
["Erreur sur la personne","Gilles Noël","1995"],
["La folie des crinolines","Jean Gagné, Serge Gagné","1995"],
["Highlander 3: The Sorcerer","Andy Morahan","1995"],
["Hollow Point","Sidney J. Furie","1995"],
["J'aime j'aime pas","Sylvie Groulx","1995"],
["Le jour des cris","Éric Gignac","1995"],
["Kids of the Round Table","Robert Tinnell","1995"],
["Liste noire","Jean-Marc Vallée","1995"],
["Motel","Pascal Maeder (en)","1995"],
["La Mule et les Émeraudes","Bashar Shbib","1995"],
["Screamers","Christian Duguay","1995"],
["Silent Hunter","Fred Williamson","1995"],
["Le Sphinx","Louis Saïa","1995"],
["Suburban Legend","Jay Ferguson","1995"],
["Witchboard 3","Peter Svatek","1995"],
["Wrong Woman","Douglas Jackson","1995"],
["Zigrail","André Turpin","1995"],
["Aire libre","Luis Armando Roche","1996"],
["La Ballade de Titus : une fable tout en couleur","Vincent De Brus","1996"],
["La Beauté, fatale et féroce","Roger Boire","1996"],
["Bullet to Beijing","George Mihalka","1996"],
["Caboose","Richard Roy","1996"],
["Cosmos","Un collectif de réalisateurs et de réalisatrices","1996"],
["Le Cri de la nuit","Jean Beaudry","1996"],
["L'Escorte","Denis Langlois","1996"],
["La Fabrication d'un meurtrier","Isabelle Poissant","1996"],
["L'Homme idéal","George Mihalka","1996"],
["L'Homme perché","Stefan Pleszczynski","1996"],
["Hot Sauce","Bashar Shbib","1996"],
["J'en suis !","Claude Fournier","1996"],
["Joyeux Calvaire","Denys Arcand","1996"],
["Karmina","Gabriel Pelletier","1996"],
["Lilies","John Greyson","1996"],
["La Marche à l'amour","Jean Gagné, Serge Gagné","1996"],
["Never Too Late","Giles Walker","1996"],
["L'Oreille d'un sourd","Mario Bolduc","1996"],
["Panic","Bashar Shbib","1996"],
["Le Polygraphe","Robert Lepage","1996"],
["Pudding chômeur","Gilles Carle","1996"],
["Rowing Through","Masato Harada","1996"],
["Le Silence des fusils","Arthur Lamothe","1996"],
["Sous-sol","Pierre Gang","1996"],
["The Strange Blues of Cowboy Red","Rick Raxlen","1996"],
["La Vengeance de la femme en noir","Roger Cantin","1996"],
["The Windsor Protocol","George Mihalka","1996"],
["L'absent","Céline Baril","1997"],
["The Assignment","Christian Duguay","1997"],
["Les Boys","Louis Saïa","1997"],
["Burnt Eden","Eugene Garcia","1997"],
["Cabaret neiges noires","Raymond Saint-Jean","1997"],
["The Call of the Wild","Peter Svatek","1997"],
["Le Ciel est à nous","Graham Guit","1997"],
["Clandestins","Denis Chouinard, Nicolas Wadimoff","1997"],
["La Comtesse de Bâton Rouge","André Forcier","1997"],
["La Conciergerie","Michel Poulette","1997"],
["De l'autre côté du cœur","Suzy Cohen","1997"],
["Habitat","René Daalder","1997"],
["Hemoglobin","Peter Svatek","1997"],
["Kayla","Nicholas Kendall","1997"],
["Maîtres anciens","Olivier Asselin","1997"],
["Matusalem II : le dernier des Beauchesne","Roger Cantin","1997"],
["Les Mille merveilles de l'univers","Jean-Michel Roux","1997"],
["Moustaches","Jim Kaufman","1997"],
["Reaper","John Bradshaw","1997"],
["Sinon, oui","Claire Simon","1997"],
["Le Siège de l'âme","Olivier Asselin","1997"],
["Stranger in the House","Rodney Gibbons","1997"],
["Strip Search","Rod Hewitt","1997"],
["Treasure Island","Peter Rowe","1997"],
["2 secondes","Manon Briand","1998"],
["L'âge de braise","Jacques Leduc","1998"],
["Aujourd'hui ou jamais","Jean Pierre Lefebvre","1998"],
["Babel","Gérard Pullicino","1998"],
["Les Boys 2","Louis Saïa","1998"],
["C't'à ton tour, Laura Cadieux","Denise Filiatrault","1998"],
["Captive","Matt Dorff","1998"],
["Le Cœur au poing","Charles Binamé","1998"],
["Dancing on the Moon","Kit Hood","1998"],
["Dead End","Douglas Jackson","1998"],
["La Déroute","Paul Tana","1998"],
["Fatal Affair","Marc S. Grenier","1998"],
["Foreign Ghosts","Hunt Hoe","1998"],
["Going to Kansas City","Pekka Mandart","1998"],
["Le grand serpent du monde","Yves Dion","1998"],
["Hasards ou Coïncidences","Claude Lelouch","1998"],
["Hathi","Philippe Gautier","1998"],
["In Her Defense","Sidney J. Furie","1998"],
["N.I.P.","François Raymond","1998"],
["Nguol thùa","Dai Sijie","1998"],
["Nico the Unicorn","Graeme Campbell","1998"],
["Nô","Robert Lepage","1998"],
["La Position de l'escargot","Michka Saäl","1998"],
["The Press Run","Robert Ditchburn","1998"],
["Quelque chose d'organique","Bertrand Bonello","1998"],
["Quiconque meurt, meurt à douleur","Robert Morin","1998"],
["Random Encounter","Douglas Jackson","1998"],
["Requiem for Murder","Douglas Jackson","1998"],
["Revoir Julie","Jeanne Crépeau","1998"],
["Running Home","Marc F. Voizard","1998"],
["Snitch","Ted Demme","1998"],
["Sublet","John Hamilton","1998"],
["Thunder Point","George Mihalka","1998"],
["Un 32 août sur Terre","Denis Villeneuve","1998"],
["Une aventure de Papyrus : La vengeance de Seth","Michel Gauthier","1998"],
["Le Violon rouge","François Girard","1998"],
["Winter Lily","Roshell Bissett","1998"],
["You Can Thank Me Later","Shimon Dotan","1998"],
["4 Days","Curtis Wehrfritz","1999"],
["Artificial Lies","Rodney Gibbons","1999"],
["L'Autobiographe amateur","Claude Fortin","1999"],
["Autour de la maison rose","Joana Hadjithomas","1999"],
["Le Dernier Souffle","Richard Ciupka","1999"],
["Elvis Gratton 2 : Miracle à Memphis","Pierre Falardeau, Julien Poulin","1999"],
["Emporte-moi","Léa Pool","1999"],
["La Fabrication des mâles","Un collectif de réalisateurs et de réalisatrices","1999"],
["Fish Out of Water","Geoffrey Edwards","1999"],
["Full Blast","Rodrigue Jean","1999"],
["Grey Owl","Richard Attenborough","1999"],
["Histoires d'hiver","François Bouvier","1999"],
["Home Team","Allan A. Goldstein","1999"],
["Laura Cadieux… la suite","Denise Filiatrault","1999"],
["Matroni et moi","Jean-Philippe Duval","1999"],
["Le Petit ciel","Jean-Sébastien Lord","1999"],
["Pin-Pon, le film","Ghyslaine Côté","1999"],
["Post mortem","Louis Bélanger","1999"],
["Quand je serai parti… vous vivrez encore","Michel Brault","1999"],
["Les Siamoises","Isabelle Hayeur","1999"],
["Souffle d'ailleurs","Martin Leclerc, Thomas Schneider","1999"],
["Souvenirs intimes","Jean Beaudin","1999"],
["Task Force","Richard Ciupka","1999"],
["Taxman","Alain Zaloum","1999"],
["Who Gets the House?","Timothy J. Nelson","1999"],
["The Witness Files","Douglas Jackson","1999"],
["Alegria","Franco Dragone","2000"],
["The Art of War","Christian Duguay","2000"],
["La beauté de Pandore","Charles Binamé","2000"],
["Blind Terror","Giles Walker","2000"],
["La bouteille","Alain DesRochers","2000"],
["Café Olé","Richard Roy","2000"],
["Deception","Max Fischer","2000"],
["Desire","Colleen Murphy","2000"],
["Les fantômes des trois Madeleine","Guylaine Dionne","2000"],
["Heavy Metal 2000","Michael Coldewey, Michel Lemire","2000"],
["Hochelaga","Michel Jetté","2000"],
["L'île de sable","Johanne Prégent","2000"],
["L'invention de l'amour","Claude Demers","2000"],
["Island of the Dead","Tim Southam","2000"],
["Jack and Ella","Brenda Keesal","2000"],
["La journée avant","David Lussier","2000"],
["The List","Sylvain Guy","2000"],
["Maelström","Denis Villeneuve","2000"],
["Méchant party","Mario Chabot","2000"],
["La moitié gauche du frigo","Philippe Falardeau","2000"],
["Les muses orphelines","Robert Favreau","2000"],
["My Little Devil","Gopi Desai","2000"],
["Ne dis rien","Simon Lacombe","2000"],
["Possible Worlds","Robert Lepage","2000"],
["Rats and Rabbits","Lewis Furey","2000"],
["La répétition","Catherine Corsini","2000"],
["Saint Jude","John L'Écuyer","2000"],
["Stardom","Denys Arcand","2000"],
["Subconscious Cruelty","Karim Hussain","2000"],
["The Tracker","Jeff Schechter","2000"],
["Trick or Treat","Marc Cayer","2000"],
["Two Thousand and None","Arto Paragamian","2000"],
["Un petit vent de panique","Pierre Greco","2000"],
["Varian's War","Lionel Chetwynd","2000"],
["La veuve de Saint-Pierre","Patrice Leconte","2000"],
["La vie après l'amour","Gabriel Pelletier","2000"],
["Xchange","Allan Moyle","2000"],
["15 février 1839","Pierre Falardeau","2001"],
["L'ange de goudron","Denis Chouinard","2001"],
["Les Boys 3","Louis Saïa","2001"],
["Des chiens dans la neige","Michel Welterlin","2001"],
["Le ciel sur la tête","Geneviève Lefebvre, André Melançon","2001"],
["Crème glacée, chocolat et autres consolations","Julie Hivon","2001"],
["Danny in the Sky","Denis Langlois","2001"],
["Dead Awake","Marc S. Grenier","2001"],
["Du pic au cœur","Céline Baril","2001"],
["La femme qui boit","Bernard Émond","2001"],
["La forteresse suspendue","Roger Cantin","2001"],
["Hidden Agenda","Marc S. Grenier","2001"],
["Hôtel des horizons","Marc Cayer","2001"],
["Karmen Geï","Joseph Gaï Ramaka","2001"],
["Karmina 2","Gabriel Pelletier","2001"],
["La loi du cochon","Érik Canuel","2001"],
["Lost and Delirious","Léa Pool","2001"],
["Mariages","Catherine Martin","2001"],
["Nuit de noces","Émile Gaudreault","2001"],
["Opération Cobra","Dominic Gagnon, Richard Jutras, Robert Morin","2001"],
["Le pornographe","Bertrand Bonello","2001"],
["Protection","John Flynn","2001"],
["So Faraway and Blue","Roy Cross","2001"],
["Stéphanie, Nathalie, Caroline et Vincent","Carl Ulrich","2001"],
["Un crabe dans la tête","André Turpin","2001"],
["Une jeune fille à la fenêtre","Francis Leclerc","2001"],
["La vérité est un mensonge","Pierre Goupil","2001"],
["Au fil de l'eau","Jeannine Gagné","2002"],
["Barbaloune","Jean Gagné, Serge Gagné","2002"],
["The Baroness and the Pig","Michael MacKenzie","2002"],
["Between Strangers","Edoardo Ponti","2002"],
["Le collectionneur","Jean Beaudin","2002"],
["Les Dangereux","Louis Saïa","2002"],
["Les Fils de Marie","Carole Laure","2002"],
["Le gambit du fou","Bruno Dubuc","2002"],
["Histoire de pen","Michel Jetté","2002"],
["Home","Phyllis Katrapani","2002"],
["Iso","Dominic Gagnon","2002"],
["Katryn's Place","Bénédicte Ronfard","2002"],
["Leaving Metropolis","Brad Fraser","2002"],
["Madame Brouette","Moussa Sene Absa","2002"],
["Le marais","Kim Nguyen","2002"],
["La Mystérieuse Mademoiselle C.","Richard Ciupka","2002"],
["Le Nèg'","Robert Morin","2002"],
["L'Odyssée d'Alice Tremblay","Denise Filiatrault","2002"],
["One Way Out","Allan A. Goldstein","2002"],
["Québec-Montréal","Ricardo Trogi","2002"],
["Régina!","Maria Sigurdardottir","2002"],
["Royal Bonbon","Charles Najman","2002"],
["Savage Messiah","Mario Azzopardi","2002"],
["Secret de banlieue","Louis Choquette","2002"],
["Séraphin : un homme et son péché","Charles Binamé","2002"],
["Sex at the End of the Millenium","Sheldon Neuberger","2002"],
["Station Nord","Jean-Claude Lord","2002"],
["Summer","Phil Price","2002"],
["La turbulence des fluides","Manon Briand","2002"],
["Women Without Wings","Nicholas Kinsey","2002"],
["Yellowknife","Rodrigue Jean","2002"],
["100 % bio","Claude Fortin","2003"],
["20h17, rue Darling","Bernard Émond","2003"],
["Annie Brocoli dans les fonds marins","Claude Brie","2003"],
["The Book of Eve","Claude Fournier","2003"],
["Comment ma mère accoucha de moi durant sa ménopause","Sébastien Rose","2003"],
["La face cachée de la lune","Robert Lepage","2003"],
["The Favourite Game","Bernar Hébert","2003"],
["Gaz Bar Blues","Louis Bélanger","2003"],
["La grande séduction","Jean-François Pouliot","2003"],
["L'homme trop pressé prend son thé à la fourchette","Sylvie Groulx","2003"],
["Les immortels","Paul Thinel","2003"],
["Les invasions barbares","Denys Arcand","2003"],
["Jack Paradise","Gilles Noël","2003"],
["Ma voisine danse le ska","Nathalie St-Pierre","2003"],
["Mambo Italiano","Émile Gaudreault","2003"],
["Le manuscrit érotique","Jean Pierre Lefebvre","2003"],
["Nez rouge","Érik Canuel","2003"],
["Père et fils","Michel Boujenah","2003"],
["La petite Lili","Claude Miller","2003"],
["Le piège d'Issoudun","Micheline Lanctôt","2003"],
["Revival Blues","Claude Gagnon","2003"],
["Saved by the Belles","Ziad Touma","2003"],
["Le secret de Cyndia","Denyse Benoît","2003"],
["A Silent Love","Federico Hidalgo","2003"],
["Sur le seuil","Éric Tessier","2003"],
["Les triplettes de Belleville","Sylvain Chomet","2003"],
["Twist","Jacob Tierney","2003"],
["Acapulco Gold","André Forcier","2004"],
["Les aimants","Yves P. Pelletier","2004"],
["The Blue Butterfly","Léa Pool","2004"],
["Le bonheur c'est une chanson triste","François Delisle","2004"],
["Bonzaïon","Danny Gilmore, Clermont Jolicoeur","2004"],
["C'est pas moi… c'est l'autre","Alain Zaloum","2004"],
["Camping sauvage","Guy A. Lepage, Sylvain Roy","2004"],
["Comment conquérir l'Amérique en une nuit?","Dany Laferrière","2004"],
["Comment devenir un trou de cul et enfin plaire aux femmes","Roger Boire","2004"],
["CQ2 (Seek You Too)","Carole Laure","2004"],
["Dans l'œil du chat","Rudy Barichello","2004"],
["Dans une galaxie près de chez vous","Claude Desrosiers","2004"],
["Le dernier tunnel","Érik Canuel","2004"],
["Dorian","Allan A. Goldstein","2004"],
["Elles étaient cinq","Ghyslaine Côté","2004"],
["Elvis Gratton XXX : la vengeance d'Elvis Wong","Pierre Falardeau","2004"],
["L'espérance","Stefan Pleszczynski","2004"],
["Éternelle","Wilhelm Liebenberg","2004"],
["Folle embellie","Dominique Cabrera","2004"],
["Goldirocks","Paula Tiberius","2004"],
["Le golem de Montréal","Isabelle Hayeur","2004"],
["Le goût des jeunes filles","John L'Écuyer","2004"],
["L'incomparable mademoiselle C.","Richard Ciupka","2004"],
["Je n'aime que toi","Claude Fournier","2004"],
["Jeunesse dans l'ombre","Gervais Germain","2004"],
["Jimmywork","Simon Sauvé","2004"],
["Littoral","Wajdi Mouawad","2004"],
["La lune viendra d'elle-même","Marie-Jan Seille","2004"],
["Ma vie en cinémascope","Denise Filiatrault","2004"],
["Mémoires affectives","Francis Leclerc","2004"],
["Monica la mitraille","Pierre Houle","2004"],
["Les moscovites","Charles Barabé","2004"],
["Nouvelle-France","Jean Beaudin","2004"],
["Ordo","Laurence Ferreira Barbosa","2004"],
["La peau blanche","Daniel Roby","2004"],
["La pension des étranges","Stella Goulet","2004"],
["Pinocchio 3000","Daniel Robichaud","2004"],
["La planque","Alexandre Chartrand","2004"],
["Premier juillet - le film","Philippe Gagnon","2004"],
["Pure","Jim Donovan","2004"],
["Vendus","Éric Tessier","2004"],
["Amnésie - L'Énigme James Brighton","Denis Langlois","2005"],
["L'audition","Luc Picard","2005"],
["Aurore","Luc Dionne","2005"],
["Barmaids","Simon Boisvert","2005"],
["Les Boys 4","George Mihalka","2005"],
["C.R.A.Z.Y.","Jean-Marc Vallée","2005"],
["Le chalet","Jarrett Mann","2005"],
["Daniel et les Superdogs","André Melançon","2005"],
["La dernière incarnation","Demian Fuica","2005"],
["Les états nordiques","Denis Côté","2005"],
["Les États-Unis d'Albert","André Forcier","2005"],
["Familia","Louise Archambault","2005"],
["Greg & Gentillon","Matthiew Klinck","2005"],
["Horloge biologique","Ricardo Trogi","2005"],
["Idole instantanée","Yves Desgagnés","2005"],
["Kamataki","Claude Gagnon","2005"],
["Latex","Pierre Lapointe","2005"],
["Maman Last Call","François Bouvier","2005"],
["Manners of Dying","Jeremy Peter Allen","2005"],
["Maurice Richard","Charles Binamé","2005"],
["Les moutons de Jacob","Jean-François Pothier","2005"],
["La neuvaine","Bernard Émond","2005"],
["Niagara Motel","Gary Yates","2005"],
["Petit pow! pow! Noël","Robert Morin","2005"],
["La pharmacie de l'espoir","François Gourd","2005"],
["Saint-Ralph","Michael McGowan","2005"],
["Saints-Martyrs-des-Damnés","Robin Aubert","2005"],
["Stories of a Gravedigger","David Aubin","2005"],
["Summer with the Ghosts","Bernd Neuburger","2005"],
["Le survenant","Érik Canuel","2005"],
["Vers le sud","Laurent Cantet","2005"],
["La vie avec mon père","Sébastien Rose","2005"],
["1st bite","Hunt Hoe","2006"],
["The 4th Life","François Miron","2006"],
["L'anus Horribilis","Bruno Dubuc","2006"],
["La belle bête","Karim Hussain","2006"],
["Black Eyed Dog","Pierre Gang","2006"],
["Bluff sou bluff","Wilfort Estimable","2006"],
["Bobby","François Blouin","2006"],
["Bon cop bad cop","Érik Canuel","2006"],
["C'est beau une ville la nuit","Richard Bohringer","2006"],
["Cadavre exquis première édition","Un collectif de réalisateurs et de réalisatrices","2006"],
["Les cavaliers de la canette","Louis Champagne","2006"],
["Cercle vicieux","Patrick Hébert","2006"],
["Cheech","Patrice Sauvé","2006"],
["Comme tout le monde","Pierre-Paul Renders","2006"],
["Congorama","Philippe Falardeau","2006"],
["Convoitises","Jean Alix Holmand","2006"],
["La coupure","Jean Châteauvert","2006"],
["De ma fenêtre, sans maison…","Maryanne Zéhil","2006"],
["Délivrez-moi","Denis Chouinard","2006"],
["The Descendant","Philippe Spurrell","2006"],
["Duo","Richard Ciupka","2006"],
["End of the Line","Maurice Devereaux","2006"],
["Les filles du botaniste","Dai Sijie","2006"],
["Gason makoklen 1","Wilfort Estimable","2006"],
["Gason makoklen 2","Wilfort Estimable","2006"],
["Le génie du crime","Louis Bélanger","2006"],
["Le guide de la petite vengeance","Jean-François Pouliot","2006"],
["Heads of Control: The Gorul Baheu Brain Expedition","Pat Tremblay","2006"],
["Histoire de famille","Michel Poulette","2006"],
["Hiver","Charles Barabé","2006"],
["The Journals of Knud Rasmussen","Norman Cohn, Zacharias Kunuk","2006"],
["Lézaureil kilyve","Charles Barabé","2006"],
["Malléables journées","Charles Barabé","2006"],
["Manga Latina: Killer on the Loose","Henrique Vera-Villaneuva","2006"],
["Martin Clear: The Whole Story","Martin Leclerc","2006"],
["The Passenger","François Rotger","2006"],
["The Point","Joshua Dorsey","2006"],
["La porte de Fersein","Éric Campeau, Simon Tardif","2006"],
["Pourquoi le dire?","Hélène Duchesneau","2006"],
["Prenez vos places","Marc Thomas-Dupuis","2006"],
["Que Dieu bénisse l'Amérique","Robert Morin","2006"],
["La rage de l'ange","Dan Bigras","2006"],
["Rechercher Victor Pellerin","Sophie Deraspe","2006"],
["Roméo et Juliette","Yves Desgagnés","2006"],
["Sans elle","Jean Beaudin","2006"],
["Le secret de ma mère","Ghyslaine Côté","2006"],
["Steel Toes","Mark Adam, David Gow","2006"],
["Sur la trace d'Igor Rizzi","Noël Mitrani","2006"],
["These Girls","John Hazlett","2006"],
["Touche pas à mon homme","Jean Rony Lubin","2006"],
["Tous les autres, sauf moi","Ann Arson","2006"],
["Un dimanche à Kigali","Robert Favreau","2006"],
["Une rame à l'eau","Jean-François Boudreault","2006"],
["La vie secrète des gens heureux","Stéphane Lapointe","2006"],
["A Year in the Death of Jack Richards","Benjamin P. Paquette","2006"],
["Les 3 p'tits cochons","Patrick Huard","2007"],
["À vos marques… party!","Frédérik D'Amours","2007"],
["Adam's Wall","Michael MacKenzie","2007"],
["L'âge des ténèbres","Denys Arcand","2007"],
["Amour, mensonges et conséquences","Jean Alix Holmand","2007"],
["The Backup Man","Doug Sutherland","2007"],
["La belle empoisonneuse","Richard Jutras","2007"],
["Bluff","Simon-Olivier Fecteau, Marc-André Lavoie","2007"],
["Borderline","Lyne Charlebois","2007"],
["La brunante","Fernand Dansereau","2007"],
["La capture","Carole Laure","2007"],
["Le cèdre penché","Rafaël Ouellet","2007"],
["Continental, un film sans fusil","Stéphane Lafleur","2007"],
["Contre toute espérance","Bernard Émond","2007"],
["Dans les villes","Catherine Martin","2007"],
["De l'autre côté","Sean Marckos","2007"],
["Échangistes","Simon Boisvert","2007"],
["Emotional Arithmetic","Paolo Barzman","2007"],
["Imitation","Federico Hidalgo","2007"],
["La lâcheté","Marc Bisaillon","2007"],
["La logique du remords","Martin Laroche","2007"],
["Ma fille mon ange","Alexis Durand-Brault","2007"],
["Ma tante Aline","Gabriel Pelletier","2007"],
["Minushi","Tyler Gibb","2007"],
["Nitro","Alain DesRochers","2007"],
["Nos vies privées","Denis Côté","2007"],
["Nos voisins Dhantsu","Alain Chicoine","2007"],
["Où vas-tu, Moshé?","Hassan Benjelloun","2007"],
["Puffball","Nicolas Roeg","2007"],
["Rêves de poussière","Laurent Salgues","2007"],
["Le ring","Anaïs Barbeau-Lavalette","2007"],
["La rivière aux castors","Philippe Calderon","2007"],
["Shake Hands with the Devil","Roger Spottiswoode","2007"],
["Silk","François Girard","2007"],
["Steak","Quentin Dupieux","2007"],
["Surviving My Mother","Émile Gaudreault","2007"],
["Toi","François Delisle","2007"],
["Un cri au bonheur","Un collectif de réalisateurs et de réalisatrices","2007"],
["Voleurs de chevaux","Micha Wald","2007"],
["Young Triffie","Mary Walsh","2007"],
["24 mesures","Jalil Lespert","2008"],
["À l'ouest de Pluton","Henry Bernadet, Myriam Verreault","2008"],
["Adagio pour un gars de bicycle","Pascale Ferland","2008"],
["Amour, destin et rock'n'roll","Dario Gasbarro","2008"],
["Babine","Luc Picard","2008"],
["Le banquet","Sébastien Rose","2008"],
["Before Tomorrow","Marie-Hélène Cousineau, Madeline Ivalu","2008"],
["C'est pas moi, je le jure!","Philippe Falardeau","2008"],
["Le cas Roberge","Raphaël Malo","2008"],
["Ce qu'il faut pour vivre","Benoît Pilon","2008"],
["Cruising Bar 2","Michel Côté, Robert Ménard","2008"],
["Dans une galaxie près de chez vous 2","Philippe Gagnon","2008"],
["Demain","Maxime Giroux","2008"],
["Derrière moi","Rafaël Ouellet","2008"],
["Le déserteur","Simon Lavoie","2008"],
["Elle veut le chaos","Denis Côté","2008"],
["En plein cœur","Stéphane Géhami","2008"],
["Le grand départ","Claude Meunier","2008"],
["La ligne brisée","Louis Choquette","2008"],
["Magique!","Philippe Muyl","2008"],
["Maman est chez le coiffeur","Léa Pool","2008"],
["Papa à la chasse aux lagopèdes","Robert Morin","2008"],
["Le piège américain","Charles Binamé","2008"],
["Les plus beaux yeux du monde","Pascal Courchesne, Charlotte Laurier","2008"],
["Restless","Amos Kollek","2008"],
["Suivre Catherine","Jeanne Crépeau","2008"],
["Tout est parfait","Yves-Christian Fournier","2008"],
["Truffe","Kim Nguyen","2008"],
["Un capitalisme sentimental","Olivier Asselin","2008"],
["Un été sans point ni coup sûr","Francis Leclerc","2008"],
["Wushu Warrior","Alain DesRochers","2008"],
["1981","Ricardo Trogi","2009"],
["3 saisons","Jim Donovan","2009"],
["40 is the new 20","Simon Boisvert","2009"],
["5150, rue des Ormes","Éric Tessier","2009"],
["À quelle heure le train pour nulle part","Robin Aubert","2009"],
["À vos marques… party! 2","Frédérik D'Amours","2009"],
["Le bonheur de Pierre","Robert Ménard","2009"],
["Cadavres","Érik Canuel","2009"],
["Carcasses","Denis Côté","2009"],
["La chambre noire","François Aubry","2009"],
["De père en flic","Émile Gaudreault","2009"],
["Dédé à travers les brumes","Jean-Philippe Duval","2009"],
["Détour","Sylvain Guy","2009"],
["Les doigts croches","Ken Scott","2009"],
["La donation","Bernard Émond","2009"],
["Grande Ourse - La clé des possibles","Patrice Sauvé","2009"],
["Les grandes chaleurs","Sophie Lorain","2009"],
["Impasse","Joël Gauthier","2009"],
["J'ai tué ma mère","Xavier Dolan","2009"],
["Je me souviens","André Forcier","2009"],
["Lost Song","Rodrigue Jean","2009"],
["Love and Savagery","John N. Smith","2009"],
["Martyrs","Pascal Laugier","2009"],
["Modern Love","Stéphane Kazandjian","2009"],
["Noémie le secret","Frédérik D'Amours","2009"],
["Nuages sur la ville","Simon Galiero","2009"],
["Les pieds dans le vide","Mariloup Wolfe","2009"],
["Polytechnique","Denis Villeneuve","2009"],
["Pour toujours les Canadiens","Sylvain Archambault","2009"],
["Refrain","Tyler Gibb","2009"],
["Sans dessein","Caroline Labrèche, Steeve Léonard","2009"],
["Serveuses demandées","Guylaine Dionne","2009"],
["Suzie","Micheline Lanctôt","2009"],
["The Timekeeper","Louis Bélanger","2009"],
["Transit","Christian de la Cortina","2009"],
["Turbid","George Fok","2009"],
["Un ange à la mer","Frédéric Dumont","2009"],
["Un cargo pour l'Afrique","Roger Cantin","2009"],
["10 1/2","Podz","2010"],
["2 fois une femme","François Delisle","2010"],
["2 frogs dans l'Ouest","Dany Papineau","2010"],
["À l'origine d'un cri","Robin Aubert","2010"],
["Les amours imaginaires","Xavier Dolan","2010"],
["L'appât","Yves Simoneau","2010"],
["Le baiser du barbu","Yves P. Pelletier","2010"],
["Cabotins","Alain DesRochers","2010"],
["La cité","Kim Nguyen","2010"],
["Curling","Denis Côté","2010"],
["La dernière fugue","Léa Pool","2010"],
["L'enfant prodige","Luc Dionne","2010"],
["Everywhere","Alexis Durand-Brault","2010"],
["Filière 13","Patrick Huard","2010"],
["Incendies","Denis Villeneuve","2010"],
["Le journal d'Aurélie Laflamme","Christian Laurence","2010"],
["Journal d'un coopérant","Robert Morin","2010"],
["Lance et compte","Frédérik D'Amours","2010"],
["Lucidité passagère","Fabrice Barrilliet","2010"],
["Mesrine - L'instinct de mort","Jean-François Richet","2010"],
["Les mots gelés","Isabelle D'Amours","2010"],
["New Denmark","Rafaël Ouellet","2010"],
["Oscar et la dame rose","Éric-Emmanuel Schmitt","2010"],
["Piché : entre ciel et terre","Sylvain Archambault","2010"],
["Le poil de la bête","Philippe Gagnon","2010"],
["Reste avec moi","Robert Ménard","2010"],
["Romaine par moins 30","Agnès Obadia","2010"],
["Route 132","Louis Bélanger","2010"],
["Les sept jours du talion","Podz","2010"],
["Les signes vitaux","Sophie Deraspe","2010"],
["Snow & Ashes","Charles-Olivier Michaud","2010"],
["Sortie 67","Jephté Bastien","2010"],
["Trois temps après la mort d'Anna","Catherine Martin","2010"],
["Tromper le silence","Julie Hivon","2010"],
["The Trotsky","Jacob Tierney","2010"],
["The Wild Hunt","Alexandre Franchi","2010"],
["Y'en aura pas de facile","Marc-André Lavoie","2010"],
["À trois, Marie s'en va","Anne-Marie Ngô","2011"],
["Angle mort","Dominic James","2011"],
["Le bonheur des autres","Jean-Philippe Pearson","2011"],
["BumRush","Michel Jetté","2011"],
["Café de Flore","Jean-Marc Vallée","2011"],
["Le colis","Gaël D'Ynglemare","2011"],
["Coteau Rouge","André Forcier","2011"],
["Décharge","Benoît Pilon","2011"],
["Die","Dominic James","2011"],
["Le divan du monde","Dominic Desjardins","2011"],
["En terrains connus","Stéphane Lafleur","2011"],
["La fille de Montréal","Jeanne Crépeau","2011"],
["French Immersion","Kevin Tierney","2011"],
["French Kiss","Sylvain Archambault","2011"],
["Frisson des collines","Richard Roy","2011"],
["Funkytown","Daniel Roby","2011"],
["Gerry","Alain DesRochers","2011"],
["Good Neighbours","Jacob Tierney","2011"],
["The High Cost of Living","Deborah Chow","2011"],
["Jaloux","Patrick Demers","2011"],
["Jo pour Jonathan","Maxime Giroux","2011"],
["The Kate Logan Affair","Noël Mitrani","2011"],
["Laurentie","Mathieu Denis, Simon Lavoie","2011"],
["Marécages","Guy Édoin","2011"],
["Monsieur Lazhar","Philippe Falardeau","2011"],
["Nuit #1","Anne Émond","2011"],
["Pour l'amour de Dieu","Micheline Lanctôt","2011"],
["La run","Demian Fuica","2011"],
["Le sens de l'humour","Émile Gaudreault","2011"],
["Shadowboxing","Jesse Klein","2011"],
["Starbuck","Ken Scott","2011"],
["Sur le rythme","Charles-Olivier Michaud","2011"],
["Une vie qui commence","Michel Monty","2011"],
["Le vendeur","Sébastien Pilote","2011"],
["La vérité","Marc Bisaillon","2011"],
["The Year Dolly Parton Was My Mom","Tara Johns","2011"],
["L'affaire Dumont","Podz","2012"],
["Après la neige","Paul Barbeau","2012"],
["Avant que mon cœur bascule","Sébastien Rose","2012"],
["Bestiaire","Denis Côté","2012"],
["Camion","Rafaël Ouellet","2012"],
["Columbarium","Steve Kerr","2012"],
["L'empire Bo$$é","Claude Desrosiers","2012"],
["Ésimésac","Luc Picard","2012"],
["The Girl in the White Coat","Darrell Wasyk","2012"],
["The Hat Goes Wild","Guy Sprung","2012"],
["Hors les murs","David Lambert","2012"],
["Inch'Allah","Anaïs Barbeau-Lavalette","2012"],
["L'incrédule","Federico Hidalgo","2012"],
["J'espère que tu vas bien","David La Haye","2012"],
["Karakara","Claude Gagnon","2012"],
["Laurence Anyways","Xavier Dolan","2012"],
["Liverpool","Manon Briand","2012"],
["Mars et Avril","Martin Villeneuve","2012"],
["Mesnak","Yves Sioui Durand","2012"],
["La mise à l'aveugle","Simon Galiero","2012"],
["Omertà","Luc Dionne","2012"],
["Les pee-wee 3D","Éric Tessier","2012"],
["La peur de l'eau","Gabriel Pelletier","2012"],
["Rebelle","Kim Nguyen","2012"],
["Roméo Onze","Ivan Grbovic","2012"],
["Thanatomorphose","Éric Falardeau","2012"],
["Le torrent","Simon Lavoie","2012"],
["Tout ce que tu possèdes","Bernard Émond","2012"],
["Une bouteille dans la mer de Gaza","Thierry Binisti","2012"],
["La vallée des larmes","Maryanne Zéhil","2012"],
["1er amour","Guillaume Sylvestre","2013"],
["Les 4 soldats","Robert Morin","2013"],
["Amsterdam","Stefan Miljevic","2013"],
["L'autre maison","Mathieu Roy","2013"],
["Catimini","Nathalie Saint-Pierre","2013"],
["Chasse au Godard d'Abbittibbi","Éric Morin","2013"],
["La cicatrice","Jimmy Larouche","2013"],
["Cyanure","Séverine Cornamusaz","2013"],
["Le démantèlement","Sébastien Pilote","2013"],
["Diego Star","Frédérick Pelletier","2013"],
["Émilie","Guillaume Lonergan","2013"],
["Finissant(e)s","Rafaël Ouellet","2013"],
["Gabrielle","Louise Archambault","2013"],
["The Good Lie","Shawn Linden","2013"],
["Home Again","Sudz Sutherland","2013"],
["Hot Dog","Marc-André Lavoie","2013"],
["Il était une fois les Boys","Richard Goudreau","2013"],
["Jappeloup","Christian Duguay","2013"],
["Lac Mystère","Érik Canuel","2013"],
["La légende de Sarila","Nancy Florence Savard","2013"],
["Louis Cyr","Daniel Roby","2013"],
["La maison du pêcheur","Alain Chartrand","2013"],
["Les manèges humains","Martin Laroche","2013"],
["Memories Corner","Audrey Fouché","2013"],
["Le météore","François Delisle","2013"],
["Misogyny/Misandry","Erik Anderson","2013"],
["Moroccan Gigolos","Ismaël Saidi","2013"],
["Ressac","Pascale Ferland","2013"],
["Roche papier ciseaux","Yan Lanouette Turgeon","2013"],
["Rouge sang","Martin Doepner","2013"],
["Sarah préfère la course","Chloé Robichaud","2013"],
["Triptyque","Robert Lepage","2013"],
["Une jeune fille","Catherine Martin","2013"],
["Vic+Flo ont vu un ours","Denis Côté","2013"],
["1987","Ricardo Trogi","2014"],
["2 temps 3 mouvements","Christophe Cousin","2014"],
["3 histoires d'Indiens","Robert Morin","2014"],
["L'ange gardien","Jean-Sébastien Lord","2014"],
["Arwad","Dominique Chila","2014"],
["Bunker","Patrick Boivin","2014"],
["Ceci n'est pas un polar","Patrick Gazé","2014"],
["Le coq de St-Victor","Pierre Greco","2014"],
["Discopathe","Renaud Gauthier","2014"],
["Dr. Cabbie","Jean-François Pouliot","2014"],
["Exil","Charles-Olivier Michaud","2014"],
["La ferme des humains","Onur Karaman","2014"],
["Le fille du Martin","Samuel Thivierge","2014"],
["La gang des hors-la-loi","Jean Beaudry","2014"],
["La garde","Sylvain Archambault","2014"],
["Gerontophilia","Bruce LaBruce","2014"],
["The Grand Seduction","Don McKellar","2014"],
["Henri Henri","Martin Talbot","2014"],
["J'espère que tu vas bien 2","David La Haye","2014"],
["Limoilou","Edgar Fritz","2014"],
["Love Projet","Carole Laure","2014"],
["Maïna","Michel Poulette","2014"],
["Les maîtres du suspense","Stéphane Lapointe","2014"],
["Meetings with a Young Poet","Rudy Barichello","2014"],
["Miraculum","Podz","2014"],
["Mommy","Xavier Dolan","2014"],
["My Guys","Joseph Antaki","2014"],
["La petite reine","Alexis Durand-Brault","2014"],
["Pour que plus jamais","Marie Ange Barbancourt","2014"],
["Qu'est-ce qu'on fait ici?","Julie Hivon","2014"],
["Que ta joie demeure","Denis Côté","2014"],
["Rédemption","Joël Gauthier","2014"],
["Le règne de la beauté","Denys Arcand","2014"],
["Rhymes for Young Ghouls","Jeff Barnaby","2014"],
["Tom à la ferme","Xavier Dolan","2014"],
["Tu dors Nicole","Stéphane Lafleur","2014"],
["Un parallèle plus tard","Sébastien Landry","2014"],
["Une vie pour deux","Luc Bourdon","2014"],
["Uvanga","Marie-Hélène Cousineau, Madeline Piujuq Ivalu","2014"],
["La voix de l'ombre","Annie Molin Vasseur","2014"],
["Le vrai du faux","Émile Gaudreault","2014"],
["Whitewash","Emanuel Hoss-Desmarais","2014"],
["L'amour au temps de la guerre civile","Rodrigue Jean","2015"],
["Anna","Charles-Olivier Michaud","2015"],
["Antoine et Marie","Jimmy Larouche","2015"],
["Aurélie Laflamme - Les pieds sur terre","Nicolas Monette","2015"],
["Autrui","Micheline Lanctôt","2015"],
["Le bruit des arbres","François Péloquin","2015"],
["Ce qu'il ne faut pas dire","Marquise Lepage","2015"],
["Chorus","François Delisle","2015"],
["Le cœur de madame Sabali","Ryan McKenna","2015"],
["Corbo","Mathieu Denis","2015"],
["Les démons","Philippe Lesage","2015"],
["Le dep","Sonia Bonspille Boileau","2015"],
["Ego Trip","Benoit Pelletier","2015"],
["Elephant Song","Charles Binamé","2015"],
["L'énergie sombre","Leonardo Fuica","2015"],
["Les Êtres chers","Anne Émond","2015"],
["Félix et Meira","Maxime Giroux","2015"],
["The Forbidden Room","Guy Maddin, Evan Johnson","2015"],
["Le garagiste","Renée Beaulieu","2015"],
["La Guerre des tuques 3D","François Brisson, Jean-François Pouliot","2015"],
["Guibord s'en va-t-en guerre","Philippe Falardeau","2015"],
["Gurov & Anna","Rafaël Ouellet","2015"],
["Je suis à toi","David Lambert","2015"],
["Le journal d'un vieil homme","Bernard Émond","2015"],
["Les Loups","Sophie Deraspe","2015"],
["Le Mirage","Ricardo Trogi","2015"],
["Noir (NWA)","Yves-Christian Fournier","2015"],
["Nouvelles, nouvelles","Olivier Godin","2015"],
["La Passion d'Augustine","Léa Pool","2015"],
["Paul à Québec","François Bouvier","2015"],
["Preggoland","Jacob Tierney","2015"],
["Le scaphandrier","Alain Vézina","2015"],
["Scratch","Sébastien Godron","2015"],
["Standstill","Majdi El-Omari","2015"],
["Turbo Kid","François Simard, Anouk et Yoann-Karl Whissell","2015"],
["Ville-Marie","Guy Édoin","2015"],
["01:54","Yan England","2016"],
["Les 3 p'tits cochons 2","Jean-François Pouliot","2016"],
["9, le film","Un collectif de réalisateurs et de réalisatrices","2016"],
["Avant les rues","Chloé Leriche","2016"],
["Boris sans Béatrice","Denis Côté","2016"],
["Ceux qui font les révolutions à moitié n'ont fait que se creuser un tombeau","Simon Lavoie, Mathieu Denis","2016"],
["La Chasse au collet","Steve Kerr","2016"],
["Chasse-Galerie : La légende","Jean-Philippe Duval","2016"],
["Déserts","Charles-André Coderre, Yann-Manuel Hernandez","2016"],
["D’encre et de sang","Alexis Fortier Gauthier, Maxim Rheault, Francis Fortin","2016"],
["Early Winter","Michael Rowe","2016"],
["Ecartée","Lawrence Côté-Collins","2016"],
["Embrasse-moi comme tu m'aimes","André Forcier","2016"],
["Endorphine","André Turpin","2016"],
["Feuilles mortes","Thierry Bouffard, Steve Landry, Édouard A. Tremblay","2016"],
["Generation Wolf","Christian de la Cortina","2016"],
["Harry : Portrait d’un détective privé","Maxime Desruisseaux","2016"],
["Juste la fin du monde","Xavier Dolan","2016"],
["King Dave","Podz","2016"],
["Là où Attila passe","Onur Karaman","2016"],
["Les Mauvaises herbes","Louis Bélanger","2016"],
["Mes ennemis","Stéphane Géhami","2016"],
["Mon ami Dino","Jimmy Larouche","2016"],
["Montréal la blanche","Bachir Bensadekk","2016"],
["Nitro Rush","Alain Desrochers","2016"],
["L'Origine des espèces","Dominic Goyer","2016"],
["Le Pacte des anges","Richard Angers","2016"],
["Pays","Chloé Robichaud","2016"],
["Prank","Vincent Biron","2016"],
["Le Rang du lion","Stéphane Beaudoin","2016"],
["The Saver","Wiebke von Carolsfeld","2016"],
["Toujours encore","Jean-François Boisvenue","2016"],
["Two Lovers and a Bear","Kim Nguyen","2016"],
["Un paradis pour tous","Robert Morin","2016"],
["Vortex","Jephté Bastien","2016"],
["Votez Bougon","Jean-François Pouliot","2016"],
["Les Affamés","Robin Aubert","2017"],
["Après coup","Noël Mitrani","2017"],
["Les arts de la parole","Olivier Godin","2017"],
["L'Autre côté de novembre","Maryanne Zéhil","2017"],
["Ballerina","Éric Warrin, Éric Summer","2017"],
["Bon Cop Bad Cop 2","Alain Desrochers","2017"],
["Boost","Darren Curtis","2017"],
["Ça sent la coupe","Patrice Sauvé","2017"],
["C'est le coeur qui meurt en dernier","Alexis Durand-Brault","2017"],
["Le Cyclotron","Olivier Asselin","2017"],
["De père en flic 2","Émile Gaudreault","2017"],
["Et au pire, on se mariera","Léa Pool","2017"],
["Innocent","Marc-André Lavoie","2017"],
["Iqaluit","Benoît Pilon","2017"],
["Junior majeur","Éric Tessier","2017"],
["Maudite Poutine","Karl Lemieux","2017"],
["Mes nuits feront écho","Sophie Goyette","2017"],
["Nelly","Anne Émond","2017"],
["Nous sommes les autres","Jean-François Asselin","2017"],
["La Petite Fille qui aimait trop les allumettes","Simon Lavoie","2017"],
["Pieds nus dans l'aube","Francis Leclerc","2017"],
["Le problème d'infiltration","Robert Morin","2017"],
["Les Rois mongols","Luc Picard","2017"],
["Tadoussac","Martin Laroche","2017"],
["Ta peau si lisse","Denis Côté","2017"],
["Le trip à trois","Nicolas Monette","2017"],
["Tuktuq","Robin Aubert","2017"],
["1991","Ricardo Trogi","2018"],
["À tous ceux qui ne me lisent pas","Yan Giroux","2018"],
["Ailleurs","Samuel Matteau","2018"],
["Allure","Jason Sachez, Carlos Sanchez","2018"],
["All You Can Eat Buddha","Ian Lagarde","2018"],
["L’amour","Marc Bisaillon","2018"],
["Another Kind of Wedding","Pat Kiely","2018"],
["Birthmarked","Emanuel Hoss-Desmarais","2018"],
["La Bolduc","François Bouvier","2018"],
["Burn Out ou la servitude volontaire","Michel Jetté","2018"],
["Charlotte a du fun","Sophie Lorain","2018"],
["Chien de garde","Sophie Dupuis","2018"],
["La Chute de l'empire américain","Denys Arcand","2018"],
["La chute de Sparte","Tristan Dubois","2018"],
["Claire l’Hiver","Sophie Bédard-Marcotte","2018"],
["La course des Tuques","François Brisson, Benoît Godbout","2018"],
["La Disparition des lucioles","Sébastien Pilote","2018"],
["Dans la brume","Daniel Roby","2018"],
["Eye on Juliet","Kim Nguyen","2018"],
["Les faux tatouages","Pascal Plante","2018"],
["Hochelaga, terre des âmes","François Girard","2018"],
["Identités","Samuel Thivierge","2018"],
["Isla Blanca","Jeanne Leblanc","2018"],
["Lemonade","Ioana Uricaru","2018"],
["Napoléon en apparte","Jeff Denis","2018"],
["Nelly et Simon : Mission Yéti","Pierre Greco, Nancy Florence Savard","2018"],
["Le nid","David Paradis","2018"],
["Origami","Patrick Demers","2018"],
["Oscillations","Ky Nam Leduc","2018"],
["Papa est devenu un lutin","Dominique Adams","2018"],
["Pour vivre ici","Bernard Émond","2018"],
["Quand l'amour se creuse un trou","Ara Ball","2018"],
["Les salopes ou le sucre naturel de la peau","Renée Beaulieu","2018"],
["Ma vie avec John F. Donovan","Xavier Dolan","2018"],
["Kristina Wagenbauer","Carla Turcotte, Natalia Dontcheva, Emmanuel Schwartz","2018"],
["Les scènes fortuites","Guillaume Lambert","2018"],
["Touched","Karl R. Hearne","2018"],
["Un printemps d’ailleurs","Xiaodan He","2018"],
["Vénus","Eisha Marjara","2018"],
["Wolfe","Francis Bordeleau","2018"],
["Yolanda","Jeannine Gagné","2018"],
["Une colonie","Geneviève Dulude-De Celles","2019"],
["La grande noirceur","Maxime Giroux","2019"],
["Malek","Guy Édoin","2019"],
["Impetus","Jennifer Alleyn","2019"],
["Mon ami Walid","Adib Alkhalidey","2019"],
["Antigone","Sophie Deraspe","2019"],
["Attaque d'un autre monde","Adrien Lorion","2019"],
["Jeune Juliette","Anne Émond","2019"],
["Journal de Bolivie - 50 ans après la mort du Che","Jules Falardeau et Jean-Philippe Nadeau Marcoux","2019"],
["Kuessipan","Myriam Verreault","2019"],
["Matthias et Maxime","Xavier Dolan","2019"],
["Répertoire des villes disparues","Denis Côté","2019"],
["Sur les traces de Bochart","Pierre Saint-Yves et Yannick Gendron","2019"],
["Menteur","Émile Gaudreault","2019"],
["Apapacho: une caresse pour l'âme","Marquise Lepage","2019"],
["La femme de mon frère","Monia Chokri","2019"],
["Les Fleurs oubliées","André Forcier","2019"],
["Jouliks","Mariloup Wolfe","2019"],
["Vivre à 100 milles à l'heure","Louis Bélanger","2019"],
["Nous sommes Gold","Éric Morin","2019"],
["Wilcox","Denis Côté","2019"],
["Je finirai en prison","Alexandre Dostie","2019"],
["Cassy","Noël Mitrani","2019"],
["Les Barbares de La Malbaie","Vincent Biron","2019"],
["Avant qu'on explose","Rémi St-Michel","2019"],
["Le rire","Martin Laroche","2020"],
["Mafia Inc.","Podz","2020"],
["14 jours, 12 nuits","Jean-Philippe Duval","2020"],
["Les nôtres","Jeanne Leblanc","2020"],
["Tu te souviendras de moi","Éric Tessier","2020"],
["Le club Vinland","Benoît Pilon","2020"],
["Target Number One","Daniel Roby","2020"],
["Le guide de la famille parfaite","Ricardo Trogi","2020"],
["Gallant : Confessions d’un tueur à gages","Luc Picard","2020"],
["La déesse des mouches à feu","Anaïs Barbeau-Lavalette","2020"]]

Cette variable, appelée ```films```, est une liste de listes.
Comme nous en informe le code ci-dessous, elle contient 1412 éléments, des listes qui comptent trois éléments chacun.

In [84]:
len(films), len(films[0]), len(films[1411])

(1412, 3, 3)

Il est très facile d'y faire une boucle pour afficher les informations qu'elle contient.

In [85]:
for film in films:
    print("Le film «{}» a été réalisé en {} par {}.".format(film[0],film[2],film[1]))

Le film «À la croisée des chemins» a été réalisé en 1943 par Paul Guèvremont.
Le film «Le Père Chopin» a été réalisé en 1945 par Fedor Ozep.
Le film «La Forteresse» a été réalisé en 1947 par Fedor Ozep.
Le film «Whispering City» a été réalisé en 1947 par Fedor Ozep.
Le film «On ne triche pas avec la vie» a été réalisé en 1949 par René Delacroix et Paul Vandenberghe.
Le film «Le Curé de village» a été réalisé en 1949 par Paul Gury.
Le film «Le Gros Bill» a été réalisé en 1949 par Jean-Yves Bigras et René Delacroix.
Le film «Un homme et son péché» a été réalisé en 1949 par Paul Gury.
Le film «Les Lumières de ma ville» a été réalisé en 1950 par Jean-Yves Bigras.
Le film «L'Inconnue de Montréal» a été réalisé en 1950 par Jean Devaivre.
Le film «Séraphin» a été réalisé en 1950 par Paul Gury.
Le film «Étienne Brûlé gibier de potence» a été réalisé en 1952 par Melburn E. Turner.
Le film «La Petite Aurore, l'enfant martyre» a été réalisé en 1952 par Jean-Yves Bigras.
Le film «Le Rossignol et l

Le film «Monica la mitraille» a été réalisé en 2004 par Pierre Houle.
Le film «Les moscovites» a été réalisé en 2004 par Charles Barabé.
Le film «Nouvelle-France» a été réalisé en 2004 par Jean Beaudin.
Le film «Ordo» a été réalisé en 2004 par Laurence Ferreira Barbosa.
Le film «La peau blanche» a été réalisé en 2004 par Daniel Roby.
Le film «La pension des étranges» a été réalisé en 2004 par Stella Goulet.
Le film «Pinocchio 3000» a été réalisé en 2004 par Daniel Robichaud.
Le film «La planque» a été réalisé en 2004 par Alexandre Chartrand.
Le film «Premier juillet - le film» a été réalisé en 2004 par Philippe Gagnon.
Le film «Pure» a été réalisé en 2004 par Jim Donovan.
Le film «Vendus» a été réalisé en 2004 par Éric Tessier.
Le film «Amnésie - L'Énigme James Brighton» a été réalisé en 2005 par Denis Langlois.
Le film «L'audition» a été réalisé en 2005 par Luc Picard.
Le film «Aurore» a été réalisé en 2005 par Luc Dionne.
Le film «Barmaids» a été réalisé en 2005 par Simon Boisvert.
L

Le film «Love Projet» a été réalisé en 2014 par Carole Laure.
Le film «Maïna» a été réalisé en 2014 par Michel Poulette.
Le film «Les maîtres du suspense» a été réalisé en 2014 par Stéphane Lapointe.
Le film «Meetings with a Young Poet» a été réalisé en 2014 par Rudy Barichello.
Le film «Miraculum» a été réalisé en 2014 par Podz.
Le film «Mommy» a été réalisé en 2014 par Xavier Dolan.
Le film «My Guys» a été réalisé en 2014 par Joseph Antaki.
Le film «La petite reine» a été réalisé en 2014 par Alexis Durand-Brault.
Le film «Pour que plus jamais» a été réalisé en 2014 par Marie Ange Barbancourt.
Le film «Qu'est-ce qu'on fait ici?» a été réalisé en 2014 par Julie Hivon.
Le film «Que ta joie demeure» a été réalisé en 2014 par Denis Côté.
Le film «Rédemption» a été réalisé en 2014 par Joël Gauthier.
Le film «Le règne de la beauté» a été réalisé en 2014 par Denys Arcand.
Le film «Rhymes for Young Ghouls» a été réalisé en 2014 par Jeff Barnaby.
Le film «Tom à la ferme» a été réalisé en 2014 

<h5 style="background:beige;text-align:center;padding:10px">La notion de compteur</h5>

Quand je fais une boucle dans une liste, j'ai pris l'habitude de créer un compteur pour savoir où mon code est rendu dans son traitement.

On peut mettre un compteur dans n'importe quelle variable. Ci-dessous, j'utilise ```n```.

Il s'agit de créer ```n``` avant que la boucle ne démarre et de lui donner la valeur de 0.

Puis, à chaque itération de la boucle, il faut lui ajouter 1.

On peut le faire ainsi: ```n = n + 1```.

Mais j'en profite pour vous montrer un opérateur unique au monde de l'informatique: ```+=```. Ce «plus-égal» signifie «remplace la valeur de ma variable par sa valeur actuelle plus le nombre qui suit».

Voici quelle forme le compteur peut prendre dans le code qu'on vient tout juste d'écrire, ci-dessus.

In [86]:
n = 0
for film in films:
    n += 1
    print("Le film «{}» (le {}e de la liste) a été réalisé en {} par {}.".format(film[0],n,film[2],film[1]))

Le film «À la croisée des chemins» (le 1e de la liste) a été réalisé en 1943 par Paul Guèvremont.
Le film «Le Père Chopin» (le 2e de la liste) a été réalisé en 1945 par Fedor Ozep.
Le film «La Forteresse» (le 3e de la liste) a été réalisé en 1947 par Fedor Ozep.
Le film «Whispering City» (le 4e de la liste) a été réalisé en 1947 par Fedor Ozep.
Le film «On ne triche pas avec la vie» (le 5e de la liste) a été réalisé en 1949 par René Delacroix et Paul Vandenberghe.
Le film «Le Curé de village» (le 6e de la liste) a été réalisé en 1949 par Paul Gury.
Le film «Le Gros Bill» (le 7e de la liste) a été réalisé en 1949 par Jean-Yves Bigras et René Delacroix.
Le film «Un homme et son péché» (le 8e de la liste) a été réalisé en 1949 par Paul Gury.
Le film «Les Lumières de ma ville» (le 9e de la liste) a été réalisé en 1950 par Jean-Yves Bigras.
Le film «L'Inconnue de Montréal» (le 10e de la liste) a été réalisé en 1950 par Jean Devaivre.
Le film «Séraphin» (le 11e de la liste) a été réalisé en 

Le film «Pourquoi le dire?» (le 933e de la liste) a été réalisé en 2006 par Hélène Duchesneau.
Le film «Prenez vos places» (le 934e de la liste) a été réalisé en 2006 par Marc Thomas-Dupuis.
Le film «Que Dieu bénisse l'Amérique» (le 935e de la liste) a été réalisé en 2006 par Robert Morin.
Le film «La rage de l'ange» (le 936e de la liste) a été réalisé en 2006 par Dan Bigras.
Le film «Rechercher Victor Pellerin» (le 937e de la liste) a été réalisé en 2006 par Sophie Deraspe.
Le film «Roméo et Juliette» (le 938e de la liste) a été réalisé en 2006 par Yves Desgagnés.
Le film «Sans elle» (le 939e de la liste) a été réalisé en 2006 par Jean Beaudin.
Le film «Le secret de ma mère» (le 940e de la liste) a été réalisé en 2006 par Ghyslaine Côté.
Le film «Steel Toes» (le 941e de la liste) a été réalisé en 2006 par Mark Adam, David Gow.
Le film «Sur la trace d'Igor Rizzi» (le 942e de la liste) a été réalisé en 2006 par Noël Mitrani.
Le film «These Girls» (le 943e de la liste) a été réalisé en 2

<img src="https://journalisme.uqam.ca/wp-content/uploads/sites/77/2020/05/bonus.png" style="text-align:center">

<h4 style="background:cyan;text-align:center;padding:10px">Boucles ```while```</h4>

Il existe un autre type de boucle, dont je me sers moins souvent.

Les boucles ```for``` sont des boucles «finies», dont on connaît la taille.

Il existe aussi des boucles «infinies» qu'on peut créer avec la commande ```while```.

Comme elles peuvent rouler à l'infini, il faut simplement prévoir une condition qui les fait arrêter. Voici un exemple.

In [87]:
n = 0
while n < 100:
    n += 1
    print(n,n**2)

1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81
10 100
11 121
12 144
13 169
14 196
15 225
16 256
17 289
18 324
19 361
20 400
21 441
22 484
23 529
24 576
25 625
26 676
27 729
28 784
29 841
30 900
31 961
32 1024
33 1089
34 1156
35 1225
36 1296
37 1369
38 1444
39 1521
40 1600
41 1681
42 1764
43 1849
44 1936
45 2025
46 2116
47 2209
48 2304
49 2401
50 2500
51 2601
52 2704
53 2809
54 2916
55 3025
56 3136
57 3249
58 3364
59 3481
60 3600
61 3721
62 3844
63 3969
64 4096
65 4225
66 4356
67 4489
68 4624
69 4761
70 4900
71 5041
72 5184
73 5329
74 5476
75 5625
76 5776
77 5929
78 6084
79 6241
80 6400
81 6561
82 6724
83 6889
84 7056
85 7225
86 7396
87 7569
88 7744
89 7921
90 8100
91 8281
92 8464
93 8649
94 8836
95 9025
96 9216
97 9409
98 9604
99 9801
100 10000


Ce que fait la boucle ci-dessus est simple. À chaque itération, elle ajoute 1 à la valeur de ```n```, puis en affiche la valeur, ainsi que son carré. Et la boucle va faire cela tant et aussi longtemps que ```n``` sera plus petit que 100. Comme cette condition est vérifiée **avant** qu'on ajoute 1 à ```n```, c'est pour cela que les valeurs «100 et 10000» sont affichées.

Ah, tiens! Je viens tout juste d'aborder avec vous l'idée des conditions. Plongeons alors tout de suite dans cette partie de la matière.

<h3 style="background:pink;text-align:center;padding:10px">Conditions</h3>

On travaille beaucoup avec des conditions en informatique pour trier ou classer des données.

Leur syntaxe générale est la suivante:
    
<code>**if** &lt;condition&gt;:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&lt;On fait quelque chose&gt;*
**elif** &lt;condition alternative&gt;:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&lt;On fait autre chose si la première condition n'est pas respectée&gt;*
**else**:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&lt;On fait encore autre chose si aucune des conditions précédentes ne sont respectées&gt;*
</code>

Vous voyez qu'il y a trois commandes possibles. Ça prend minimalement un ```if``` pour tester au moins une condition.

Ça peut être suivi par un ```elif```, qui est une contraction de *else if* («alors si»), dans les cas où on veut vérifier une autre condition.

Ça peut aussi se terminer par un ```else``` («alors») si aucune des conditions ne se vérifie.

Vous remarquez aussi que l'**indentation** est présente, comme dans les boucles. Seul le code qui se trouve *sous* la condition (après les deux points (```:```)) et qui est indenté sera exécuté par la condition.

Commençons par un premier exemple. Dans notre grande variable ```films```, si vous souhaitez n'afficher que les films réalisés l'année de votre naissance, par exemple, vous pourriez inclure dans votre boucle ```for``` une condition exprimée de la façon suivante:

In [88]:
for film in films:
    if film[2] == "1966":
        print(film)

['Carnaval en chute libre', 'Guy Bouchard', '1966']
['La Douzième heure', 'Jean Martimbeau', '1966']
['Footsteps in the Snow (Des pas sur la neige)', 'Martin Green', '1966']
['Yul 871', 'Jacques Godbout', '1966']


Vous avez peut-être remarqué qu'il y a deux symboles «égal» (```==```). C'est qu'en informatique, un seul symbole «égal» (```=```) ne signifie pas «égale». Cela signifie «je déclare que telle valeur sera placée dans telle variable». La véritable égalité est testée avec le double égal.

Voici les autres opérateurs que vous pouvez utiliser dans les conditions.

<table>
<thead>
  <tr style="text-align:center;">
    <th>Opérateur</th>
    <th>Description</th>
    <th>Exemple</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td style="text-align:left;">**==**</td>
    <td style="text-align:left;">Égal</td>
    <td style="text-align:right;">```if a == b:```</td>
  </tr>
  <tr>
    <td style="text-align:left;">**!=**</td>
    <td style="text-align:left;">Pas égal</td>
    <td style="text-align:right;">```if a != b:```</td>
  </tr>
  <tr>
    <td style="text-align:left;">**&gt;**</td>
    <td style="text-align:left;">Plus grand</td>
    <td style="text-align:right;">```if a > b:```</td>
  </tr>
  <tr>
    <td style="text-align:left;">**&gt;=**</td>
    <td style="text-align:left;">Plus grand ou égal</td>
    <td style="text-align:right;">```if a >= b:```</td>
  </tr>
  <tr>
    <td style="text-align:left;">**&lt;**</td>
    <td style="text-align:left;">Plus petit</td>
    <td style="text-align:right;">```if a < b:```</td>
  </tr>
  <tr>
    <td style="text-align:left;">**&lt;=**</td>
    <td style="text-align:left;">Plus petit ou égal</td>
    <td style="text-align:right;">```if a <= b:```</td>
  </tr>
  <tr>
    <td style="text-align:left;">**and**</td>
    <td style="text-align:left;">et<br>*Fonctionne si tous les tests sont vrais*</td>
    <td style="text-align:right;">```if x > 1000 and x < 2000:```</td>
  </tr>
  <tr>
    <td style="text-align:left;">**or**</td>
    <td style="text-align:left;">ou<br>*Fonctionne si l'un des tests est vrai*</td>
    <td style="text-align:right;">```if x < 300 or y > 300:```</td>
  </tr>
  <tr>
    <td style="text-align:left;">**not**</td>
    <td style="text-align:left;">non<br>*Fonctionne si le test est faux*</td>
    <td style="text-align:right;">```if not(x > 5 and y < 10):```</td>
  </tr>
  <tr>
    <td style="text-align:left;">**in**</td>
    <td style="text-align:left;">Est présent dans</td>
    <td style="text-align:right;">```if "texte" in z:```</td>
  </tr>
  <tr>
    <td style="text-align:left;">**not in**</td>
    <td style="text-align:left;">N'est pas présent dans</td>
    <td style="text-align:right;">```if "texte" not in z:```</td>
  </tr>
</tbody>
</table>

Par exemple, si vous cherchez les films réalisés par Guy A. Lepage, vous pourriez être tenté d'écrire:

In [89]:
for film in films:
    if film[1] == "Guy A. Lepage":
        print(film)

Mais ça ne donne aucun résultat. C'est que M. Lepage a signé un film avec un autre réalisateur. Ainsi, il n'arrive jamais que le 2e élément de la variable ```film``` contienne très exactement et uniquement «Guy A. Lepage». Le code suivant est donc préférable:

In [90]:
for film in films:
    if "Guy A. Lepage" in film[1]:
        print(film)

['Camping sauvage', 'Guy A. Lepage, Sylvain Roy', '2004']


Je vous ai aussi montré comment trier les films réalisés en 2000 ou après. Il s'agit de se servir du 3e élément de la variable ```film``` (```film[2]```) qui contient l'année où chaque film a été réalisé. Cette variable est de type texte. Ainsi, on peut en extraire les deux premiers caractères, comme on l'a fait ci-dessus avec du texte. Il suffit d'ajouter ```[:2]``` à ```film[2]```.

Les films contenus dans la liste ont été réalisés entre 1943 et 2020. Les deux premiers caractères de ces années ne peuvent être que «19» ou «20». Ainsi, il suffit de faire la condition ci-dessous pour ne faire afficher que les films réalisés en 2000 ou après:

In [91]:
for film in films:
    if film[2][:2] == "20":
        print("Le film {} a été réalisé en {}.".format(film[0],film[2]))

Le film Alegria a été réalisé en 2000.
Le film The Art of War a été réalisé en 2000.
Le film La beauté de Pandore a été réalisé en 2000.
Le film Blind Terror a été réalisé en 2000.
Le film La bouteille a été réalisé en 2000.
Le film Café Olé a été réalisé en 2000.
Le film Deception a été réalisé en 2000.
Le film Desire a été réalisé en 2000.
Le film Les fantômes des trois Madeleine a été réalisé en 2000.
Le film Heavy Metal 2000 a été réalisé en 2000.
Le film Hochelaga a été réalisé en 2000.
Le film L'île de sable a été réalisé en 2000.
Le film L'invention de l'amour a été réalisé en 2000.
Le film Island of the Dead a été réalisé en 2000.
Le film Jack and Ella a été réalisé en 2000.
Le film La journée avant a été réalisé en 2000.
Le film The List a été réalisé en 2000.
Le film Maelström a été réalisé en 2000.
Le film Méchant party a été réalisé en 2000.
Le film La moitié gauche du frigo a été réalisé en 2000.
Le film Les muses orphelines a été réalisé en 2000.
Le film My Little Devil a

Je vous ai ensuite montré une technique semblable pour trier les films réalisés avant les années 1960. Essayons d'appliquer la même chose, mais aux films réalisés durant les années 1980 et 1990.

Cela implique l'utilisation de la fonction ```int()``` pour transformer en nombres les trois premiers caractères des années.

In [92]:
for film in films:
    if int(film[2][:3]) > 197 and int(film[2][:3]) <= 199:
        print("Le film {} a été réalisé en {}.".format(film[0],film[2]))

Le film Agency a été réalisé en 1980.
Le film Atlantic City, U.S.A. a été réalisé en 1980.
Le film Les bons débarras a été réalisé en 1980.
Le film Ça peut pas être l'hiver on n'a même pas eu d'été a été réalisé en 1980.
Le film Le chef se déniaise a été réalisé en 1980.
Le film Contrecœur a été réalisé en 1980.
Le film La cuisine rouge a été réalisé en 1980.
Le film Fantastica a été réalisé en 1980.
Le film Final Assignment a été réalisé en 1980.
Le film Les grands enfants a été réalisé en 1980.
Le film Hog Wild a été réalisé en 1980.
Le film L'homme à tout faire a été réalisé en 1980.
Le film Hot Dogs a été réalisé en 1980.
Le film The Lucky Star a été réalisé en 1980.
Le film Pinball Summer a été réalisé en 1980.
Le film Strass café a été réalisé en 1980.
Le film Suzanne a été réalisé en 1980.
Le film Terror Train a été réalisé en 1980.
Le film Thetford au milieu de notre vie a été réalisé en 1980.
Le film Les beaux souvenirs a été réalisé en 1981.
Le film Black Mirror a été réalisé

Enfin, pour vous donner un exemple de l'utilisation de ```if```, de ```elif``` et de ```else```, je vais me servir de la variable ```olympiques```.

Le code ci-dessous vérifie trois conditions différentes, pour produire quatre résultats différents.

In [93]:
for annee in olympiques:
    if annee == 1916:
        print("Les jeux de {} ont été annulés en raison de la Première Guerre mondiale".format(annee))
    elif annee == 1940 or annee == 1944:
        print("Les jeux de {} ont été annulés en raison de la Seconde Guerre mondiale".format(annee))
    elif annee == 2020:
        print("Les jeux de {} ont été reportés en raison de la pandémie de COVID-19".format(annee))
    else:
        print("Les jeux de {} ont bel et bien eu lieu".format(annee))

Les jeux de 1896 ont bel et bien eu lieu
Les jeux de 1900 ont bel et bien eu lieu
Les jeux de 1904 ont bel et bien eu lieu
Les jeux de 1908 ont bel et bien eu lieu
Les jeux de 1912 ont bel et bien eu lieu
Les jeux de 1916 ont été annulés en raison de la Première Guerre mondiale
Les jeux de 1920 ont bel et bien eu lieu
Les jeux de 1924 ont bel et bien eu lieu
Les jeux de 1928 ont bel et bien eu lieu
Les jeux de 1932 ont bel et bien eu lieu
Les jeux de 1936 ont bel et bien eu lieu
Les jeux de 1940 ont été annulés en raison de la Seconde Guerre mondiale
Les jeux de 1944 ont été annulés en raison de la Seconde Guerre mondiale
Les jeux de 1948 ont bel et bien eu lieu
Les jeux de 1952 ont bel et bien eu lieu
Les jeux de 1956 ont bel et bien eu lieu
Les jeux de 1960 ont bel et bien eu lieu
Les jeux de 1964 ont bel et bien eu lieu
Les jeux de 1968 ont bel et bien eu lieu
Les jeux de 1972 ont bel et bien eu lieu
Les jeux de 1976 ont bel et bien eu lieu
Les jeux de 1980 ont bel et bien eu lieu
L